import { Lesson, Verb } from './types';
import { lesson1 } from './data/lesson1';
import { lesson2 } from './data/lesson2';
import { lesson3 } from './data/lesson3';

export const VERBS: Record<string, Verb> = {
  // ==========================================
  // TYPE 1: IMMUTABLE VERBS (V1 = V2 = V3)
  // ==========================================
  cut: { base: 'cut', v2: 'cut', v3: 'cut', s: 'cuts', ing: 'cutting', type: 'immutable', meaning: 'To divide with a sharp instrument' },
  put: { base: 'put', v2: 'put', v3: 'put', s: 'puts', ing: 'putting', type: 'immutable', meaning: 'To move something to a specific place' },
  set: { base: 'set', v2: 'set', v3: 'set', s: 'sets', ing: 'setting', type: 'immutable', meaning: 'To put something in a specific place or state' },
  hit: { base: 'hit', v2: 'hit', v3: 'hit', s: 'hits', ing: 'hitting', type: 'immutable', meaning: 'To strike forcefully' },
  let: { base: 'let', v2: 'let', v3: 'let', s: 'lets', ing: 'letting', type: 'immutable', meaning: 'To allow or permit' },
  cost: { base: 'cost', v2: 'cost', v3: 'cost', s: 'costs', ing: 'costing', type: 'immutable', meaning: 'To require a payment of money' },
  hurt: { base: 'hurt', v2: 'hurt', v3: 'hurt', s: 'hurts', ing: 'hurting', type: 'immutable', meaning: 'To cause pain or injury' },
  shut: { base: 'shut', v2: 'shut', v3: 'shut', s: 'shuts', ing: 'shutting', type: 'immutable', meaning: 'To close something' },
  quit: { base: 'quit', v2: 'quit', v3: 'quit', s: 'quits', ing: 'quitting', type: 'immutable', meaning: 'To stop doing something or leave a job' },
  spread: { base: 'spread', v2: 'spread', v3: 'spread', s: 'spreads', ing: 'spreading', type: 'immutable', meaning: 'To open out or extend over an area' },
  bet: { base: 'bet', v2: 'bet', v3: 'bet', s: 'bets', ing: 'betting', type: 'immutable', meaning: 'To risk money on a result' },
  burst: { base: 'burst', v2: 'burst', v3: 'burst', s: 'bursts', ing: 'bursting', type: 'immutable', meaning: 'To break open suddenly' },
  cast: { base: 'cast', v2: 'cast', v3: 'cast', s: 'casts', ing: 'casting', type: 'immutable', meaning: 'To throw something forcibly' },
  read: { base: 'read', v2: 'read', v3: 'read', s: 'reads', ing: 'reading', type: 'immutable', meaning: 'To look at and comprehend written words' },
  fit: { base: 'fit', v2: 'fit', v3: 'fit', s: 'fits', ing: 'fitting', type: 'immutable', meaning: 'To be of the right shape or size' },
  upset: { base: 'upset', v2: 'upset', v3: 'upset', s: 'upsets', ing: 'upsetting', type: 'immutable', meaning: 'To make someone unhappy or worried' },
  beset: { base: 'beset', v2: 'beset', v3: 'beset', s: 'besets', ing: 'besetting', type: 'immutable', meaning: 'To trouble or threaten persistently' },
  bid: { base: 'bid', v2: 'bid', v3: 'bid', s: 'bids', ing: 'bidding', type: 'immutable', meaning: 'To offer a price for something' },
  broadcast: { base: 'broadcast', v2: 'broadcast', v3: 'broadcast', s: 'broadcasts', ing: 'broadcasting', type: 'immutable', meaning: 'To transmit by radio or television' },
  shed: { base: 'shed', v2: 'shed', v3: 'shed', s: 'sheds', ing: 'shedding', type: 'immutable', meaning: 'To lose or drop (skin, leaves, hair)' },
  slit: { base: 'slit', v2: 'slit', v3: 'slit', s: 'slits', ing: 'slitting', type: 'immutable', meaning: 'To make a long, straight cut' },
  split: { base: 'split', v2: 'split', v3: 'split', s: 'splits', ing: 'splitting', type: 'immutable', meaning: 'To break into parts forcibly' },
  thrust: { base: 'thrust', v2: 'thrust', v3: 'thrust', s: 'thrusts', ing: 'thrusting', type: 'immutable', meaning: 'To push suddenly or violently' },
  wed: { base: 'wed', v2: 'wed', v3: 'wed', s: 'weds', ing: 'wedding', type: 'immutable', meaning: 'To marry' },
  preset: { base: 'preset', v2: 'preset', v3: 'preset', s: 'presets', ing: 'presetting', type: 'immutable', meaning: 'To set a timer or control in advance' },
  reset: { base: 'reset', v2: 'reset', v3: 'reset', s: 'resets', ing: 'resetting', type: 'immutable', meaning: 'To set again or differently' },

  // ==========================================
  // TYPE 2: REGULAR VERBS (+ed)
  // ==========================================
  walk: { base: 'walk', v2: 'walked', v3: 'walked', s: 'walks', ing: 'walking', type: 'regular', meaning: 'To move at a regular pace on foot' },
  play: { base: 'play', v2: 'played', v3: 'played', s: 'plays', ing: 'playing', type: 'regular', meaning: 'To engage in activity for enjoyment' },
  cook: { base: 'cook', v2: 'cooked', v3: 'cooked', s: 'cooks', ing: 'cooking', type: 'regular', meaning: 'To prepare food by heating it' },
  ask: { base: 'ask', v2: 'asked', v3: 'asked', s: 'asks', ing: 'asking', type: 'regular', meaning: 'To say something to get an answer' },
  call: { base: 'call', v2: 'called', v3: 'called', s: 'calls', ing: 'calling', type: 'regular', meaning: 'To cry out or contact by phone' },
  help: { base: 'help', v2: 'helped', v3: 'helped', s: 'helps', ing: 'helping', type: 'regular', meaning: 'To make it easier for someone to do something' },
  look: { base: 'look', v2: 'looked', v3: 'looked', s: 'looks', ing: 'looking', type: 'regular', meaning: 'To direct one\'s gaze' },
  move: { base: 'move', v2: 'moved', v3: 'moved', s: 'moves', ing: 'moving', type: 'regular', meaning: 'To go to a different place or position' },
  live: { base: 'live', v2: 'lived', v3: 'lived', s: 'lives', ing: 'living', type: 'regular', meaning: 'To remain alive or reside in a place' },
  start: { base: 'start', v2: 'started', v3: 'started', s: 'starts', ing: 'starting', type: 'regular', meaning: 'To begin doing something' },
  talk: { base: 'talk', v2: 'talked', v3: 'talked', s: 'talks', ing: 'talking', type: 'regular', meaning: 'To speak in order to give information' },
  use: { base: 'use', v2: 'used', v3: 'used', s: 'uses', ing: 'using', type: 'regular', meaning: 'To take or hold something as a means of accomplishing a task' },
  want: { base: 'want', v2: 'wanted', v3: 'wanted', s: 'wants', ing: 'wanting', type: 'regular', meaning: 'To have a desire to possess or do something' },
  work: { base: 'work', v2: 'worked', v3: 'worked', s: 'works', ing: 'working', type: 'regular', meaning: 'To engage in activity to achieve a result' },
  add: { base: 'add', v2: 'added', v3: 'added', s: 'adds', ing: 'adding', type: 'regular', meaning: 'To join something to something else' },
  agree: { base: 'agree', v2: 'agreed', v3: 'agreed', s: 'agrees', ing: 'agreeing', type: 'regular', meaning: 'To have the same opinion' },
  allow: { base: 'allow', v2: 'allowed', v3: 'allowed', s: 'allows', ing: 'allowing', type: 'regular', meaning: 'To give permission to do something' },
  answer: { base: 'answer', v2: 'answered', v3: 'answered', s: 'answers', ing: 'answering', type: 'regular', meaning: 'To say something in reaction to a question' },
  appear: { base: 'appear', v2: 'appeared', v3: 'appeared', s: 'appears', ing: 'appearing', type: 'regular', meaning: 'To come into sight' },
  arrive: { base: 'arrive', v2: 'arrived', v3: 'arrived', s: 'arrives', ing: 'arriving', type: 'regular', meaning: 'To reach a destination' },
  believe: { base: 'believe', v2: 'believed', v3: 'believed', s: 'believes', ing: 'believing', type: 'regular', meaning: 'To accept something as true' },
  belong: { base: 'belong', v2: 'belonged', v3: 'belonged', s: 'belongs', ing: 'belonging', type: 'regular', meaning: 'To be the property of' },
  borrow: { base: 'borrow', v2: 'borrowed', v3: 'borrowed', s: 'borrows', ing: 'borrowing', type: 'regular', meaning: 'To take and use something with the intention of returning it' },
  carry: { base: 'carry', v2: 'carried', v3: 'carried', s: 'carries', ing: 'carrying', type: 'regular', meaning: 'To support and move something from one place to another' },
  cause: { base: 'cause', v2: 'caused', v3: 'caused', s: 'causes', ing: 'causing', type: 'regular', meaning: 'To make something happen' },
  change: { base: 'change', v2: 'changed', v3: 'changed', s: 'changes', ing: 'changing', type: 'regular', meaning: 'To make or become different' },
  check: { base: 'check', v2: 'checked', v3: 'checked', s: 'checks', ing: 'checking', type: 'regular', meaning: 'To examine something' },
  clean: { base: 'clean', v2: 'cleaned', v3: 'cleaned', s: 'cleans', ing: 'cleaning', type: 'regular', meaning: 'To make something free of dirt' },
  close: { base: 'close', v2: 'closed', v3: 'closed', s: 'closes', ing: 'closing', type: 'regular', meaning: 'To shut something' },

  // ==========================================
  // TYPE 3: IRREGULAR VERBS (SHAPESHIFTERS)
  // ==========================================
  arise: { base: 'arise', v2: 'arose', v3: 'arisen', s: 'arises', ing: 'arising', type: 'irregular', meaning: 'To emerge or become apparent' },
  awake: { base: 'awake', v2: 'awoke', v3: 'awoken', s: 'awakes', ing: 'awaking', type: 'irregular', meaning: 'To stop sleeping' },
  be: { base: 'be', v2: 'was/were', v3: 'been', s: 'is', ing: 'being', type: 'irregular', meaning: 'To exist or occur' },
  bear: { base: 'bear', v2: 'bore', v3: 'born', s: 'bears', ing: 'bearing', type: 'irregular', meaning: 'To carry or support' },
  beat: { base: 'beat', v2: 'beat', v3: 'beaten', s: 'beats', ing: 'beating', type: 'irregular', meaning: 'To strike repeatedly' },
  become: { base: 'become', v2: 'became', v3: 'become', s: 'becomes', ing: 'becoming', type: 'irregular', meaning: 'To begin to be' },
  begin: { base: 'begin', v2: 'began', v3: 'begun', s: 'begins', ing: 'beginning', type: 'irregular', meaning: 'To start something' },
  bend: { base: 'bend', v2: 'bent', v3: 'bent', s: 'bends', ing: 'bending', type: 'irregular', meaning: 'To shape or force into a curve' },
  bind: { base: 'bind', v2: 'bound', v3: 'bound', s: 'binds', ing: 'binding', type: 'irregular', meaning: 'To tie or fasten tightly' },
  bite: { base: 'bite', v2: 'bit', v3: 'bitten', s: 'bites', ing: 'biting', type: 'irregular', meaning: 'To use teeth to cut into something' },
  bleed: { base: 'bleed', v2: 'bled', v3: 'bled', s: 'bleeds', ing: 'bleeding', type: 'irregular', meaning: 'To lose blood' },
  blow: { base: 'blow', v2: 'blew', v3: 'blown', s: 'blows', ing: 'blowing', type: 'irregular', meaning: 'To expel air' },
  break: { base: 'break', v2: 'broke', v3: 'broken', s: 'breaks', ing: 'breaking', type: 'irregular', meaning: 'To separate into pieces suddenly' },
  breed: { base: 'breed', v2: 'bred', v3: 'bred', s: 'breeds', ing: 'breeding', type: 'irregular', meaning: 'To produce offspring' },
  bring: { base: 'bring', v2: 'brought', v3: 'brought', s: 'brings', ing: 'bringing', type: 'irregular', meaning: 'To take or carry to a place' },
  build: { base: 'build', v2: 'built', v3: 'built', s: 'builds', ing: 'building', type: 'irregular', meaning: 'To construct something' },
  buy: { base: 'buy', v2: 'bought', v3: 'bought', s: 'buys', ing: 'buying', type: 'irregular', meaning: 'To obtain in exchange for payment' },
  catch: { base: 'catch', v2: 'caught', v3: 'caught', s: 'catches', ing: 'catching', type: 'irregular', meaning: 'To intercept and hold' },
  choose: { base: 'choose', v2: 'chose', v3: 'chosen', s: 'chooses', ing: 'choosing', type: 'irregular', meaning: 'To pick out from alternatives' },
  cling: { base: 'cling', v2: 'clung', v3: 'clung', s: 'clings', ing: 'clinging', type: 'irregular', meaning: 'To hold on tightly' },
  come: { base: 'come', v2: 'came', v3: 'come', s: 'comes', ing: 'coming', type: 'irregular', meaning: 'To move or travel towards the speaker' },
  creep: { base: 'creep', v2: 'crept', v3: 'crept', s: 'creeps', ing: 'creeping', type: 'irregular', meaning: 'To move slowly and carefully' },
  deal: { base: 'deal', v2: 'dealt', v3: 'dealt', s: 'deals', ing: 'dealing', type: 'irregular', meaning: 'To distribute or take action' },
  dig: { base: 'dig', v2: 'dug', v3: 'dug', s: 'digs', ing: 'digging', type: 'irregular', meaning: 'To break up and move earth' },
  do: { base: 'do', v2: 'did', v3: 'done', s: 'does', ing: 'doing', type: 'irregular', meaning: 'To perform an action' },
  draw: { base: 'draw', v2: 'drew', v3: 'drawn', s: 'draws', ing: 'drawing', type: 'irregular', meaning: 'To produce a picture or pull something' },
  dream: { base: 'dream', v2: 'dreamt', v3: 'dreamt', s: 'dreams', ing: 'dreaming', type: 'irregular', meaning: 'To experience images during sleep' },
  drink: { base: 'drink', v2: 'drank', v3: 'drunk', s: 'drinks', ing: 'drinking', type: 'irregular', meaning: 'To swallow liquid' },
  drive: { base: 'drive', v2: 'drove', v3: 'driven', s: 'drives', ing: 'driving', type: 'irregular', meaning: 'To operate a vehicle' },
  eat: { base: 'eat', v2: 'ate', v3: 'eaten', s: 'eats', ing: 'eating', type: 'irregular', meaning: 'To consume food' },
  fall: { base: 'fall', v2: 'fell', v3: 'fallen', s: 'falls', ing: 'falling', type: 'irregular', meaning: 'To drop downwards' },
  feed: { base: 'feed', v2: 'fed', v3: 'fed', s: 'feeds', ing: 'feeding', type: 'irregular', meaning: 'To give food to' },
  feel: { base: 'feel', v2: 'felt', v3: 'felt', s: 'feels', ing: 'feeling', type: 'irregular', meaning: 'To experience an emotion or sensation' },
  fight: { base: 'fight', v2: 'fought', v3: 'fought', s: 'fights', ing: 'fighting', type: 'irregular', meaning: 'To engage in conflict' },
  find: { base: 'find', v2: 'found', v3: 'found', s: 'finds', ing: 'finding', type: 'irregular', meaning: 'To discover something' },
  flee: { base: 'flee', v2: 'fled', v3: 'fled', s: 'flees', ing: 'fleeing', type: 'irregular', meaning: 'To run away from danger' },
  fling: { base: 'fling', v2: 'flung', v3: 'flung', s: 'flings', ing: 'flinging', type: 'irregular', meaning: 'To throw forcefully' },
  fly: { base: 'fly', v2: 'flew', v3: 'flown', s: 'flies', ing: 'flying', type: 'irregular', meaning: 'To move through the air' },
  forbid: { base: 'forbid', v2: 'forbade', v3: 'forbidden', s: 'forbids', ing: 'forbidding', type: 'irregular', meaning: 'To order not to do something' },
  forget: { base: 'forget', v2: 'forgot', v3: 'forgotten', s: 'forgets', ing: 'forgetting', type: 'irregular', meaning: 'To fail to remember' },
  forsake: { base: 'forsake', v2: 'forsook', v3: 'forsaken', s: 'forsakes', ing: 'forsaking', type: 'irregular', meaning: 'To abandon or give up' },
  freeze: { base: 'freeze', v2: 'froze', v3: 'frozen', s: 'freezes', ing: 'freezing', type: 'irregular', meaning: 'To turn into ice' },
  get: { base: 'get', v2: 'got', v3: 'got', s: 'gets', ing: 'getting', type: 'irregular', meaning: 'To receive or obtain' },
  give: { base: 'give', v2: 'gave', v3: 'given', s: 'gives', ing: 'giving', type: 'irregular', meaning: 'To transfer possession freely' },
  go: { base: 'go', v2: 'went', v3: 'gone', s: 'goes', ing: 'going', type: 'irregular', meaning: 'To move from one place to another' },
  grind: { base: 'grind', v2: 'ground', v3: 'ground', s: 'grinds', ing: 'grinding', type: 'irregular', meaning: 'To reduce to small particles' },
  grow: { base: 'grow', v2: 'grew', v3: 'grown', s: 'grows', ing: 'growing', type: 'irregular', meaning: 'To increase in size' },
  hang: { base: 'hang', v2: 'hung', v3: 'hung', s: 'hangs', ing: 'hanging', type: 'irregular', meaning: 'To suspend from above' },
  have: { base: 'have', v2: 'had', v3: 'had', s: 'has', ing: 'having', type: 'irregular', meaning: 'To possess or own' },
  hear: { base: 'hear', v2: 'heard', v3: 'heard', s: 'hears', ing: 'hearing', type: 'irregular', meaning: 'To perceive sound' },
  hide: { base: 'hide', v2: 'hid', v3: 'hidden', s: 'hides', ing: 'hiding', type: 'irregular', meaning: 'To put out of sight' },
  hold: { base: 'hold', v2: 'held', v3: 'held', s: 'holds', ing: 'holding', type: 'irregular', meaning: 'To grasp or carry' },
  keep: { base: 'keep', v2: 'kept', v3: 'kept', s: 'keeps', ing: 'keeping', type: 'irregular', meaning: 'To retain possession of' },
  kneel: { base: 'kneel', v2: 'knelt', v3: 'knelt', s: 'kneels', ing: 'kneeling', type: 'irregular', meaning: 'To go down on knees' },
  know: { base: 'know', v2: 'knew', v3: 'known', s: 'knows', ing: 'knowing', type: 'irregular', meaning: 'To be aware of through observation' },
  lay: { base: 'lay', v2: 'laid', v3: 'laid', s: 'lays', ing: 'laying', type: 'irregular', meaning: 'To put something down gently' },
  lead: { base: 'lead', v2: 'led', v3: 'led', s: 'leads', ing: 'leading', type: 'irregular', meaning: 'To show the way' },
  leap: { base: 'leap', v2: 'leapt', v3: 'leapt', s: 'leaps', ing: 'leaping', type: 'irregular', meaning: 'To jump high or far' },
  leave: { base: 'leave', v2: 'left', v3: 'left', s: 'leaves', ing: 'leaving', type: 'irregular', meaning: 'To go away from' },
  lend: { base: 'lend', v2: 'lent', v3: 'lent', s: 'lends', ing: 'lending', type: 'irregular', meaning: 'To allow usage temporarily' },
  lie: { base: 'lie', v2: 'lay', v3: 'lain', s: 'lies', ing: 'lying', type: 'irregular', meaning: 'To be in a horizontal position' },
  light: { base: 'light', v2: 'lit', v3: 'lit', s: 'lights', ing: 'lighting', type: 'irregular', meaning: 'To provide with light or ignite' },
  lose: { base: 'lose', v2: 'lost', v3: 'lost', s: 'loses', ing: 'losing', type: 'irregular', meaning: 'To be deprived of something' },
  make: { base: 'make', v2: 'made', v3: 'made', s: 'makes', ing: 'making', type: 'irregular', meaning: 'To form or create' },
  mean: { base: 'mean', v2: 'meant', v3: 'meant', s: 'means', ing: 'meaning', type: 'irregular', meaning: 'To intend to convey' },
  meet: { base: 'meet', v2: 'met', v3: 'met', s: 'meets', ing: 'meeting', type: 'irregular', meaning: 'To come into the presence of' },
  pay: { base: 'pay', v2: 'paid', v3: 'paid', s: 'pays', ing: 'paying', type: 'irregular', meaning: 'To give money for goods/services' },
  ride: { base: 'ride', v2: 'rode', v3: 'ridden', s: 'rides', ing: 'riding', type: 'irregular', meaning: 'To sit on and control a vehicle/animal' },
  ring: { base: 'ring', v2: 'rang', v3: 'rung', s: 'rings', ing: 'ringing', type: 'irregular', meaning: 'To make a clear resonant sound' },
  rise: { base: 'rise', v2: 'rose', v3: 'risen', s: 'rises', ing: 'rising', type: 'irregular', meaning: 'To move upwards' },
  run: { base: 'run', v2: 'ran', v3: 'run', s: 'runs', ing: 'running', type: 'irregular', meaning: 'To move faster than walking' },
  say: { base: 'say', v2: 'said', v3: 'said', s: 'says', ing: 'saying', type: 'irregular', meaning: 'To utter words' },
  see: { base: 'see', v2: 'saw', v3: 'seen', s: 'sees', ing: 'seeing', type: 'irregular', meaning: 'To perceive with the eyes' },
  seek: { base: 'seek', v2: 'sought', v3: 'sought', s: 'seeks', ing: 'seeking', type: 'irregular', meaning: 'To attempt to find' },
  sell: { base: 'sell', v2: 'sold', v3: 'sold', s: 'sells', ing: 'selling', type: 'irregular', meaning: 'To exchange goods for money' },
  send: { base: 'send', v2: 'sent', v3: 'sent', s: 'sends', ing: 'sending', type: 'irregular', meaning: 'To cause to go to a place' },
  shake: { base: 'shake', v2: 'shook', v3: 'shaken', s: 'shakes', ing: 'shaking', type: 'irregular', meaning: 'To move quickly back and forth' },
  shine: { base: 'shine', v2: 'shone', v3: 'shone', s: 'shines', ing: 'shining', type: 'irregular', meaning: 'To emit light' },
  shoot: { base: 'shoot', v2: 'shot', v3: 'shot', s: 'shoots', ing: 'shooting', type: 'irregular', meaning: 'To fire a gun or weapon' },
  show: { base: 'show', v2: 'showed', v3: 'shown', s: 'shows', ing: 'showing', type: 'irregular', meaning: 'To allow to be seen' },
  shrink: { base: 'shrink', v2: 'shrank', v3: 'shrunk', s: 'shrinks', ing: 'shrinking', type: 'irregular', meaning: 'To become smaller' },
  sing: { base: 'sing', v2: 'sang', v3: 'sung', s: 'sings', ing: 'singing', type: 'irregular', meaning: 'To make musical sounds with voice' },
  sink: { base: 'sink', v2: 'sank', v3: 'sunk', s: 'sinks', ing: 'sinking', type: 'irregular', meaning: 'To go down below the surface' },
  sit: { base: 'sit', v2: 'sat', v3: 'sat', s: 'sits', ing: 'sitting', type: 'irregular', meaning: 'To be in a seated position' },
  slay: { base: 'slay', v2: 'slew', v3: 'slain', s: 'slays', ing: 'slaying', type: 'irregular', meaning: 'To kill in a violent way' },
  sleep: { base: 'sleep', v2: 'slept', v3: 'slept', s: 'sleeps', ing: 'sleeping', type: 'irregular', meaning: 'To rest in a state of unconsciousness' },
  slide: { base: 'slide', v2: 'slid', v3: 'slid', s: 'slides', ing: 'sliding', type: 'irregular', meaning: 'To move smoothly along a surface' },
  sling: { base: 'sling', v2: 'slung', v3: 'slung', s: 'slings', ing: 'slinging', type: 'irregular', meaning: 'To throw from a sling' },
  slink: { base: 'slink', v2: 'slunk', v3: 'slunk', s: 'slinks', ing: 'slinking', type: 'irregular', meaning: 'To move stealthily' },
  speak: { base: 'speak', v2: 'spoke', v3: 'spoken', s: 'speaks', ing: 'speaking', type: 'irregular', meaning: 'To say something' },
  spend: { base: 'spend', v2: 'spent', v3: 'spent', s: 'spends', ing: 'spending', type: 'irregular', meaning: 'To pay out money or time' },
  spin: { base: 'spin', v2: 'spun', v3: 'spun', s: 'spins', ing: 'spinning', type: 'irregular', meaning: 'To turn or whirl round quickly' },
  spit: { base: 'spit', v2: 'spat', v3: 'spat', s: 'spits', ing: 'spitting', type: 'irregular', meaning: 'To eject saliva' },
  spring: { base: 'spring', v2: 'sprang', v3: 'sprung', s: 'springs', ing: 'springing', type: 'irregular', meaning: 'To jump suddenly' },
  stand: { base: 'stand', v2: 'stood', v3: 'stood', s: 'stands', ing: 'standing', type: 'irregular', meaning: 'To be in an upright position' },
  steal: { base: 'steal', v2: 'stole', v3: 'stolen', s: 'steals', ing: 'stealing', type: 'irregular', meaning: 'To take without permission' },
  stick: { base: 'stick', v2: 'stuck', v3: 'stuck', s: 'sticks', ing: 'sticking', type: 'irregular', meaning: 'To adhere or attach' },
  sting: { base: 'sting', v2: 'stung', v3: 'stung', s: 'stings', ing: 'stinging', type: 'irregular', meaning: 'To wound with a sting' },
  stink: { base: 'stink', v2: 'stank', v3: 'stunk', s: 'stinks', ing: 'stinking', type: 'irregular', meaning: 'To have a strong unpleasant smell' },
  stride: { base: 'stride', v2: 'strode', v3: 'stridden', s: 'strides', ing: 'striding', type: 'irregular', meaning: 'To walk with long steps' },
  strike: { base: 'strike', v2: 'struck', v3: 'struck', s: 'strikes', ing: 'striking', type: 'irregular', meaning: 'To hit forcibly' },
  strive: { base: 'strive', v2: 'strove', v3: 'striven', s: 'strives', ing: 'striving', type: 'irregular', meaning: 'To make great efforts' },
  swear: { base: 'swear', v2: 'swore', v3: 'sworn', s: 'swears', ing: 'swearing', type: 'irregular', meaning: 'To state on oath or curse' },
  sweep: { base: 'sweep', v2: 'swept', v3: 'swept', s: 'sweeps', ing: 'sweeping', type: 'irregular', meaning: 'To clean with a broom' },
  swim: { base: 'swim', v2: 'swam', v3: 'swum', s: 'swims', ing: 'swimming', type: 'irregular', meaning: 'To move through water' },
  swing: { base: 'swing', v2: 'swung', v3: 'swung', s: 'swings', ing: 'swinging', type: 'irregular', meaning: 'To move back and forth' },
  take: { base: 'take', v2: 'took', v3: 'taken', s: 'takes', ing: 'taking', type: 'irregular', meaning: 'To get hold of' },
  teach: { base: 'teach', v2: 'taught', v3: 'taught', s: 'teaches', ing: 'teaching', type: 'irregular', meaning: 'To instruct or educate' },
  tear: { base: 'tear', v2: 'tore', v3: 'torn', s: 'tears', ing: 'tearing', type: 'irregular', meaning: 'To pull apart force' },
  tell: { base: 'tell', v2: 'told', v3: 'told', s: 'tells', ing: 'telling', type: 'irregular', meaning: 'To communicate information' },
  think: { base: 'think', v2: 'thought', v3: 'thought', s: 'thinks', ing: 'thinking', type: 'irregular', meaning: 'To use the mind to consider' },
  throw: { base: 'throw', v2: 'threw', v3: 'thrown', s: 'throws', ing: 'throwing', type: 'irregular', meaning: 'To propel with force' },
  tread: { base: 'tread', v2: 'trod', v3: 'trodden', s: 'treads', ing: 'treading', type: 'irregular', meaning: 'To walk on' },
  undergo: { base: 'undergo', v2: 'underwent', v3: 'undergone', s: 'undergoes', ing: 'undergoing', type: 'irregular', meaning: 'To experience something' },
  understand: { base: 'understand', v2: 'understood', v3: 'understood', s: 'understands', ing: 'understanding', type: 'irregular', meaning: 'To comprehend meaning' },
  uphold: { base: 'uphold', v2: 'upheld', v3: 'upheld', s: 'upholds', ing: 'upholding', type: 'irregular', meaning: 'To confirm or support' },
  wake: { base: 'wake', v2: 'woke', v3: 'woken', s: 'wakes', ing: 'waking', type: 'irregular', meaning: 'To stop sleeping' },
  wear: { base: 'wear', v2: 'wore', v3: 'worn', s: 'wears', ing: 'wearing', type: 'irregular', meaning: 'To have on one\'s body' },
  weave: { base: 'weave', v2: 'wove', v3: 'woven', s: 'weaves', ing: 'weaving', type: 'irregular', meaning: 'To form fabric by interlacing' },
  weep: { base: 'weep', v2: 'wept', v3: 'wept', s: 'weeps', ing: 'weeping', type: 'irregular', meaning: 'To cry tears' },
  win: { base: 'win', v2: 'won', v3: 'won', s: 'wins', ing: 'winning', type: 'irregular', meaning: 'To be successful' },
  wind: { base: 'wind', v2: 'wound', v3: 'wound', s: 'winds', ing: 'winding', type: 'irregular', meaning: 'To twist or encircle' },
  withdraw: { base: 'withdraw', v2: 'withdrew', v3: 'withdrawn', s: 'withdraws', ing: 'withdrawing', type: 'irregular', meaning: 'To remove or take away' },
  write: { base: 'write', v2: 'wrote', v3: 'written', s: 'writes', ing: 'writing', type: 'irregular', meaning: 'To mark letters on a surface' },
  wring: { base: 'wring', v2: 'wrung', v3: 'wrung', s: 'wrings', ing: 'wringing', type: 'irregular', meaning: 'To twist and squeeze' },
};

export const LESSONS: Lesson[] = [lesson1, lesson2, lesson3];