
import { Lesson, Verb } from './types';
import { lesson1 } from './data/lesson1';
import { lesson2 } from './data/lesson2';
import { lesson3 } from './data/lesson3';

export const VERBS: Record<string, Verb> = {
  // ==========================================
  // TYPE 1: IMMUTABLE VERBS (V1 = V2 = V3)
  // ==========================================
  beset: { base: 'beset', v2: 'beset', v3: 'beset', s: 'besets', ing: 'besetting', type: 'immutable', meaning: 'To trouble or threaten persistently' },
  bet: { base: 'bet', v2: 'bet', v3: 'bet', s: 'bets', ing: 'betting', type: 'immutable', meaning: 'To risk money on a result' },
  bid: { base: 'bid', v2: 'bid', v3: 'bid', s: 'bids', ing: 'bidding', type: 'immutable', meaning: 'To offer a price for something' },
  broadcast: { base: 'broadcast', v2: 'broadcast', v3: 'broadcast', s: 'broadcasts', ing: 'broadcasting', type: 'immutable', meaning: 'To transmit by radio or television' },
  burst: { base: 'burst', v2: 'burst', v3: 'burst', s: 'bursts', ing: 'bursting', type: 'immutable', meaning: 'To break open suddenly' },
  cast: { base: 'cast', v2: 'cast', v3: 'cast', s: 'casts', ing: 'casting', type: 'immutable', meaning: 'To throw something forcibly' },
  cost: { base: 'cost', v2: 'cost', v3: 'cost', s: 'costs', ing: 'costing', type: 'immutable', meaning: 'To require a payment of money' },
  cut: { base: 'cut', v2: 'cut', v3: 'cut', s: 'cuts', ing: 'cutting', type: 'immutable', meaning: 'To divide with a sharp instrument' },
  forecast: { base: 'forecast', v2: 'forecast', v3: 'forecast', s: 'forecasts', ing: 'forecasting', type: 'immutable', meaning: 'To predict the weather or a trend' },
  hit: { base: 'hit', v2: 'hit', v3: 'hit', s: 'hits', ing: 'hitting', type: 'immutable', meaning: 'To strike forcefully' },
  hurt: { base: 'hurt', v2: 'hurt', v3: 'hurt', s: 'hurts', ing: 'hurting', type: 'immutable', meaning: 'To cause pain or injury' },
  let: { base: 'let', v2: 'let', v3: 'let', s: 'lets', ing: 'letting', type: 'immutable', meaning: 'To allow or permit' },
  misread: { base: 'misread', v2: 'misread', v3: 'misread', s: 'misreads', ing: 'misreading', type: 'immutable', meaning: 'To read or interpret incorrectly' },
  outbid: { base: 'outbid', v2: 'outbid', v3: 'outbid', s: 'outbids', ing: 'outbidding', type: 'immutable', meaning: 'To offer a higher price than others' },
  outspread: { base: 'outspread', v2: 'outspread', v3: 'outspread', s: 'outspreads', ing: 'outspreading', type: 'immutable', meaning: 'To spread out fully' },
  overcast: { base: 'overcast', v2: 'overcast', v3: 'overcast', s: 'overcasts', ing: 'overcasting', type: 'immutable', meaning: 'To cover with clouds or shadow' },
  overspread: { base: 'overspread', v2: 'overspread', v3: 'overspread', s: 'overspreads', ing: 'overspreading', type: 'immutable', meaning: 'To spread over the surface' },
  preset: { base: 'preset', v2: 'preset', v3: 'preset', s: 'presets', ing: 'presetting', type: 'immutable', meaning: 'To set a timer or control in advance' },
  put: { base: 'put', v2: 'put', v3: 'put', s: 'puts', ing: 'putting', type: 'immutable', meaning: 'To move something to a specific place' },
  read: { base: 'read', v2: 'read', v3: 'read', s: 'reads', ing: 'reading', type: 'immutable', meaning: 'To look at and comprehend written words' },
  recast: { base: 'recast', v2: 'recast', v3: 'recast', s: 'recasts', ing: 'recasting', type: 'immutable', meaning: 'To cast again or differently' },
  reread: { base: 'reread', v2: 'reread', v3: 'reread', s: 'rereads', ing: 'rereading', type: 'immutable', meaning: 'To read something again' },
  reset: { base: 'reset', v2: 'reset', v3: 'reset', s: 'resets', ing: 'resetting', type: 'immutable', meaning: 'To set again or differently' },
  rid: { base: 'rid', v2: 'rid', v3: 'rid', s: 'rids', ing: 'ridding', type: 'immutable', meaning: 'To free someone from something unwanted' },
  set: { base: 'set', v2: 'set', v3: 'set', s: 'sets', ing: 'setting', type: 'immutable', meaning: 'To put something in a specific place or state' },
  shed: { base: 'shed', v2: 'shed', v3: 'shed', s: 'sheds', ing: 'shedding', type: 'immutable', meaning: 'To lose or drop (skin, leaves, hair)' },
  shut: { base: 'shut', v2: 'shut', v3: 'shut', s: 'shuts', ing: 'shutting', type: 'immutable', meaning: 'To close something' },
  slit: { base: 'slit', v2: 'slit', v3: 'slit', s: 'slits', ing: 'slitting', type: 'immutable', meaning: 'To make a long, straight cut' },
  split: { base: 'split', v2: 'split', v3: 'split', s: 'splits', ing: 'splitting', type: 'immutable', meaning: 'To break into parts forcibly' },
  spread: { base: 'spread', v2: 'spread', v3: 'spread', s: 'spreads', ing: 'spreading', type: 'immutable', meaning: 'To open out or extend over an area' },
  thrust: { base: 'thrust', v2: 'thrust', v3: 'thrust', s: 'thrusts', ing: 'thrusting', type: 'immutable', meaning: 'To push suddenly or violently' },
  underbid: { base: 'underbid', v2: 'underbid', v3: 'underbid', s: 'underbids', ing: 'underbidding', type: 'immutable', meaning: 'To bid lower than others' },
  undercut: { base: 'undercut', v2: 'undercut', v3: 'undercut', s: 'undercuts', ing: 'undercutting', type: 'immutable', meaning: 'To offer goods at a lower price' },
  unknit: { base: 'unknit', v2: 'unknit', v3: 'unknit', s: 'unknits', ing: 'unknitting', type: 'immutable', meaning: 'To unravel something knitted' },
  upset: { base: 'upset', v2: 'upset', v3: 'upset', s: 'upsets', ing: 'upsetting', type: 'immutable', meaning: 'To make someone unhappy or worried' },
  wed: { base: 'wed', v2: 'wed', v3: 'wed', s: 'weds', ing: 'wedding', type: 'immutable', meaning: 'To marry' },

  // ==========================================
  // TYPE 2: REGULAR VERBS (+ed pattern)
  // ==========================================
  add: { base: 'add', v2: 'added', v3: 'added', s: 'adds', ing: 'adding', type: 'regular', meaning: 'To join something to something else' },
  agree: { base: 'agree', v2: 'agreed', v3: 'agreed', s: 'agrees', ing: 'agreeing', type: 'regular', meaning: 'To have the same opinion' },
  allow: { base: 'allow', v2: 'allowed', v3: 'allowed', s: 'allows', ing: 'allowing', type: 'regular', meaning: 'To give permission to do something' },
  answer: { base: 'answer', v2: 'answered', v3: 'answered', s: 'answers', ing: 'answering', type: 'regular', meaning: 'To say something in reaction to a question' },
  appear: { base: 'appear', v2: 'appeared', v3: 'appeared', s: 'appears', ing: 'appearing', type: 'regular', meaning: 'To come into sight' },
  arrive: { base: 'arrive', v2: 'arrived', v3: 'arrived', s: 'arrives', ing: 'arriving', type: 'regular', meaning: 'To reach a destination' },
  ask: { base: 'ask', v2: 'asked', v3: 'asked', s: 'asks', ing: 'asking', type: 'regular', meaning: 'To say something to get an answer' },
  believe: { base: 'believe', v2: 'believed', v3: 'believed', s: 'believes', ing: 'believing', type: 'regular', meaning: 'To accept something as true' },
  belong: { base: 'belong', v2: 'belonged', v3: 'belonged', s: 'belongs', ing: 'belonging', type: 'regular', meaning: 'To be the property of' },
  borrow: { base: 'borrow', v2: 'borrowed', v3: 'borrowed', s: 'borrows', ing: 'borrowing', type: 'regular', meaning: 'To take and use something temporarily' },
  call: { base: 'call', v2: 'called', v3: 'called', s: 'calls', ing: 'calling', type: 'regular', meaning: 'To cry out or contact by phone' },
  carry: { base: 'carry', v2: 'carried', v3: 'carried', s: 'carries', ing: 'carrying', type: 'regular', meaning: 'To support and move something from one place to another' },
  cause: { base: 'cause', v2: 'caused', v3: 'caused', s: 'causes', ing: 'causing', type: 'regular', meaning: 'To make something happen' },
  change: { base: 'change', v2: 'changed', v3: 'changed', s: 'changes', ing: 'changing', type: 'regular', meaning: 'To make or become different' },
  check: { base: 'check', v2: 'checked', v3: 'checked', s: 'checks', ing: 'checking', type: 'regular', meaning: 'To examine something' },
  clean: { base: 'clean', v2: 'cleaned', v3: 'cleaned', s: 'cleans', ing: 'cleaning', type: 'regular', meaning: 'To make something free of dirt' },
  close: { base: 'close', v2: 'closed', v3: 'closed', s: 'closes', ing: 'closing', type: 'regular', meaning: 'To shut something' },
  compare: { base: 'compare', v2: 'compared', v3: 'compared', s: 'compares', ing: 'comparing', type: 'regular', meaning: 'To estimate the similarity between things' },
  complain: { base: 'complain', v2: 'complained', v3: 'complained', s: 'complains', ing: 'complaining', type: 'regular', meaning: 'To express dissatisfaction' },
  complete: { base: 'complete', v2: 'completed', v3: 'completed', s: 'completes', ing: 'completing', type: 'regular', meaning: 'To finish making or doing something' },
  contain: { base: 'contain', v2: 'contained', v3: 'contained', s: 'contains', ing: 'containing', type: 'regular', meaning: 'To have or hold within' },
  continue: { base: 'continue', v2: 'continued', v3: 'continued', s: 'continues', ing: 'continuing', type: 'regular', meaning: 'To keep on doing something' },
  cook: { base: 'cook', v2: 'cooked', v3: 'cooked', s: 'cooks', ing: 'cooking', type: 'regular', meaning: 'To prepare food by heating it' },
  copy: { base: 'copy', v2: 'copied', v3: 'copied', s: 'copies', ing: 'copying', type: 'regular', meaning: 'To make a duplicate of something' },
  correct: { base: 'correct', v2: 'corrected', v3: 'corrected', s: 'corrects', ing: 'correcting', type: 'regular', meaning: 'To fix a mistake' },
  count: { base: 'count', v2: 'counted', v3: 'counted', s: 'counts', ing: 'counting', type: 'regular', meaning: 'To determine the total number of items' },
  cry: { base: 'cry', v2: 'cried', v3: 'cried', s: 'cries', ing: 'crying', type: 'regular', meaning: 'To shed tears' },
  dance: { base: 'dance', v2: 'danced', v3: 'danced', s: 'dances', ing: 'dancing', type: 'regular', meaning: 'To move rhythmically to music' },
  decide: { base: 'decide', v2: 'decided', v3: 'decided', s: 'decides', ing: 'deciding', type: 'regular', meaning: 'To make a choice from options' },
  deliver: { base: 'deliver', v2: 'delivered', v3: 'delivered', s: 'delivers', ing: 'delivering', type: 'regular', meaning: 'To bring and hand over' },
  describe: { base: 'describe', v2: 'described', v3: 'described', s: 'describes', ing: 'describing', type: 'regular', meaning: 'To give a detailed account of' },
  design: { base: 'design', v2: 'designed', v3: 'designed', s: 'designs', ing: 'designing', type: 'regular', meaning: 'To create a plan or drawing' },
  destroy: { base: 'destroy', v2: 'destroyed', v3: 'destroyed', s: 'destroys', ing: 'destroying', type: 'regular', meaning: 'To damage something beyond repair' },
  die: { base: 'die', v2: 'died', v3: 'died', s: 'dies', ing: 'dying', type: 'regular', meaning: 'To stop living' },
  discuss: { base: 'discuss', v2: 'discussed', v3: 'discussed', s: 'discusses', ing: 'discussing', type: 'regular', meaning: 'To talk about something in detail' },
  dress: { base: 'dress', v2: 'dressed', v3: 'dressed', s: 'dresses', ing: 'dressing', type: 'regular', meaning: 'To put on clothes' },
  dry: { base: 'dry', v2: 'dried', v3: 'dried', s: 'dries', ing: 'drying', type: 'regular', meaning: 'To remove moisture' },
  earn: { base: 'earn', v2: 'earned', v3: 'earned', s: 'earns', ing: 'earning', type: 'regular', meaning: 'To receive money for work' },
  end: { base: 'end', v2: 'ended', v3: 'ended', s: 'ends', ing: 'ending', type: 'regular', meaning: 'To finish or reach a conclusion' },
  enjoy: { base: 'enjoy', v2: 'enjoyed', v3: 'enjoyed', s: 'enjoys', ing: 'enjoying', type: 'regular', meaning: 'To take pleasure in' },
  enter: { base: 'enter', v2: 'entered', v3: 'entered', s: 'enters', ing: 'entering', type: 'regular', meaning: 'To go or come into a place' },
  expect: { base: 'expect', v2: 'expected', v3: 'expected', s: 'expects', ing: 'expecting', type: 'regular', meaning: 'To regard something as likely to happen' },
  explain: { base: 'explain', v2: 'explained', v3: 'explained', s: 'explains', ing: 'explaining', type: 'regular', meaning: 'To make something clear or easy to understand' },
  fail: { base: 'fail', v2: 'failed', v3: 'failed', s: 'fails', ing: 'failing', type: 'regular', meaning: 'To be unsuccessful in achieving a goal' },
  fear: { base: 'fear', v2: 'feared', v3: 'feared', s: 'fears', ing: 'fearing', type: 'regular', meaning: 'To be afraid of' },
  fill: { base: 'fill', v2: 'filled', v3: 'filled', s: 'fills', ing: 'filling', type: 'regular', meaning: 'To make something full' },
  finish: { base: 'finish', v2: 'finished', v3: 'finished', s: 'finishes', ing: 'finishing', type: 'regular', meaning: 'To bring to an end' },
  fit: { base: 'fit', v2: 'fitted', v3: 'fitted', s: 'fits', ing: 'fitting', type: 'regular', meaning: 'To be of the right shape or size' },
  fix: { base: 'fix', v2: 'fixed', v3: 'fixed', s: 'fixes', ing: 'fixing', type: 'regular', meaning: 'To repair something broken' },
  follow: { base: 'follow', v2: 'followed', v3: 'followed', s: 'follows', ing: 'following', type: 'regular', meaning: 'To go or come after someone' },
  form: { base: 'form', v2: 'formed', v3: 'formed', s: 'forms', ing: 'forming', type: 'regular', meaning: 'To create or organize' },
  guess: { base: 'guess', v2: 'guessed', v3: 'guessed', s: 'guesses', ing: 'guessing', type: 'regular', meaning: 'To estimate without sufficient information' },
  happen: { base: 'happen', v2: 'happened', v3: 'happened', s: 'happens', ing: 'happening', type: 'regular', meaning: 'To occur by chance or otherwise' },
  hate: { base: 'hate', v2: 'hated', v3: 'hated', s: 'hates', ing: 'hating', type: 'regular', meaning: 'To dislike intensely' },
  help: { base: 'help', v2: 'helped', v3: 'helped', s: 'helps', ing: 'helping', type: 'regular', meaning: 'To assist someone' },
  hope: { base: 'hope', v2: 'hoped', v3: 'hoped', s: 'hopes', ing: 'hoping', type: 'regular', meaning: 'To want something to happen' },
  ignore: { base: 'ignore', v2: 'ignored', v3: 'ignored', s: 'ignores', ing: 'ignoring', type: 'regular', meaning: 'To refuse to take notice of' },
  imagine: { base: 'imagine', v2: 'imagined', v3: 'imagined', s: 'imagines', ing: 'imagining', type: 'regular', meaning: 'To form a mental image' },
  improve: { base: 'improve', v2: 'improved', v3: 'improved', s: 'improves', ing: 'improving', type: 'regular', meaning: 'To make or become better' },
  include: { base: 'include', v2: 'included', v3: 'included', s: 'includes', ing: 'including', type: 'regular', meaning: 'To contain as part of a whole' },
  increase: { base: 'increase', v2: 'increased', v3: 'increased', s: 'increases', ing: 'increasing', type: 'regular', meaning: 'To become greater in size' },
  inform: { base: 'inform', v2: 'informed', v3: 'informed', s: 'informs', ing: 'informing', type: 'regular', meaning: 'To give facts or information' },
  intend: { base: 'intend', v2: 'intended', v3: 'intended', s: 'intends', ing: 'intending', type: 'regular', meaning: 'To have as a plan or purpose' },
  interest: { base: 'interest', v2: 'interested', v3: 'interested', s: 'interests', ing: 'interesting', type: 'regular', meaning: 'To excite the curiosity of' },
  invite: { base: 'invite', v2: 'invited', v3: 'invited', s: 'invites', ing: 'inviting', type: 'regular', meaning: 'To ask someone to an event' },
  join: { base: 'join', v2: 'joined', v3: 'joined', s: 'joins', ing: 'joining', type: 'regular', meaning: 'To connect or fasten together' },
  jump: { base: 'jump', v2: 'jumped', v3: 'jumped', s: 'jumps', ing: 'jumping', type: 'regular', meaning: 'To push oneself off the ground' },
  kick: { base: 'kick', v2: 'kicked', v3: 'kicked', s: 'kicks', ing: 'kicking', type: 'regular', meaning: 'To strike with the foot' },
  kill: { base: 'kill', v2: 'killed', v3: 'killed', s: 'kills', ing: 'killing', type: 'regular', meaning: 'To cause the death of' },
  knit: { base: 'knit', v2: 'knitted', v3: 'knitted', s: 'knits', ing: 'knitting', type: 'regular', meaning: 'To make a garment by interlocking loops of wool' },
  knock: { base: 'knock', v2: 'knocked', v3: 'knocked', s: 'knocks', ing: 'knocking', type: 'regular', meaning: 'To strike a surface noisily' },
  laugh: { base: 'laugh', v2: 'laughed', v3: 'laughed', s: 'laughs', ing: 'laughing', type: 'regular', meaning: 'To make sounds showing amusement' },
  lift: { base: 'lift', v2: 'lifted', v3: 'lifted', s: 'lifts', ing: 'lifting', type: 'regular', meaning: 'To raise to a higher position' },
  listen: { base: 'listen', v2: 'listened', v3: 'listened', s: 'listens', ing: 'listening', type: 'regular', meaning: 'To give attention to sound' },
  live: { base: 'live', v2: 'lived', v3: 'lived', s: 'lives', ing: 'living', type: 'regular', meaning: 'To remain alive or reside in a place' },
  lock: { base: 'lock', v2: 'locked', v3: 'locked', s: 'locks', ing: 'locking', type: 'regular', meaning: 'To fasten with a key' },
  look: { base: 'look', v2: 'looked', v3: 'looked', s: 'looks', ing: 'looking', type: 'regular', meaning: 'To direct one\'s gaze' },
  love: { base: 'love', v2: 'loved', v3: 'loved', s: 'loves', ing: 'loving', type: 'regular', meaning: 'To feel deep affection for' },
  manage: { base: 'manage', v2: 'managed', v3: 'managed', s: 'manages', ing: 'managing', type: 'regular', meaning: 'To be in charge of' },
  mark: { base: 'mark', v2: 'marked', v3: 'marked', s: 'marks', ing: 'marking', type: 'regular', meaning: 'To make a visible impression on' },
  marry: { base: 'marry', v2: 'married', v3: 'married', s: 'marries', ing: 'marrying', type: 'regular', meaning: 'To join in marriage' },
  match: { base: 'match', v2: 'matched', v3: 'matched', s: 'matches', ing: 'matching', type: 'regular', meaning: 'To correspond or be similar' },
  measure: { base: 'measure', v2: 'measured', v3: 'measured', s: 'measures', ing: 'measuring', type: 'regular', meaning: 'To ascertain the size or amount of' },
  mention: { base: 'mention', v2: 'mentioned', v3: 'mentioned', s: 'mentions', ing: 'mentioning', type: 'regular', meaning: 'To refer to something briefly' },
  miss: { base: 'miss', v2: 'missed', v3: 'missed', s: 'misses', ing: 'missing', type: 'regular', meaning: 'To fail to hit, reach, or see' },
  mix: { base: 'mix', v2: 'mixed', v3: 'mixed', s: 'mixes', ing: 'mixing', type: 'regular', meaning: 'To combine or blend together' },
  move: { base: 'move', v2: 'moved', v3: 'moved', s: 'moves', ing: 'moving', type: 'regular', meaning: 'To go to a different place or position' },
  name: { base: 'name', v2: 'named', v3: 'named', s: 'names', ing: 'naming', type: 'regular', meaning: 'To give a name to' },
  need: { base: 'need', v2: 'needed', v3: 'needed', s: 'needs', ing: 'needing', type: 'regular', meaning: 'To require something' },
  note: { base: 'note', v2: 'noted', v3: 'noted', s: 'notes', ing: 'noting', type: 'regular', meaning: 'To record something in writing' },
  notice: { base: 'notice', v2: 'noticed', v3: 'noticed', s: 'notices', ing: 'noticing', type: 'regular', meaning: 'To become aware of' },
  number: { base: 'number', v2: 'numbered', v3: 'numbered', s: 'numbers', ing: 'numbering', type: 'regular', meaning: 'To assign a number to' },
  offer: { base: 'offer', v2: 'offered', v3: 'offered', s: 'offers', ing: 'offering', type: 'regular', meaning: 'To present for acceptance' },
  open: { base: 'open', v2: 'opened', v3: 'opened', s: 'opens', ing: 'opening', type: 'regular', meaning: 'To move something to allow access' },
  order: { base: 'order', v2: 'ordered', v3: 'ordered', s: 'orders', ing: 'ordering', type: 'regular', meaning: 'To command or request goods' },
  organise: { base: 'organise', v2: 'organised', v3: 'organised', s: 'organises', ing: 'organising', type: 'regular', meaning: 'To arrange in an orderly way' },
  pack: { base: 'pack', v2: 'packed', v3: 'packed', s: 'packs', ing: 'packing', type: 'regular', meaning: 'To put items into a container' },
  paint: { base: 'paint', v2: 'painted', v3: 'painted', s: 'paints', ing: 'painting', type: 'regular', meaning: 'To apply liquid color to a surface' },
  pass: { base: 'pass', v2: 'passed', v3: 'passed', s: 'passes', ing: 'passing', type: 'regular', meaning: 'To move past or through' },
  pause: { base: 'pause', v2: 'paused', v3: 'paused', s: 'pauses', ing: 'pausing', type: 'regular', meaning: 'To stop briefly' },
  perform: { base: 'perform', v2: 'performed', v3: 'performed', s: 'performs', ing: 'performing', type: 'regular', meaning: 'To carry out a task or entertainment' },
  phone: { base: 'phone', v2: 'phoned', v3: 'phoned', s: 'phones', ing: 'phoning', type: 'regular', meaning: 'To call someone by telephone' },
  pick: { base: 'pick', v2: 'picked', v3: 'picked', s: 'picks', ing: 'picking', type: 'regular', meaning: 'To choose or detach from a plant' },
  place: { base: 'place', v2: 'placed', v3: 'placed', s: 'places', ing: 'placing', type: 'regular', meaning: 'To put in a particular position' },
  plan: { base: 'plan', v2: 'planned', v3: 'planned', s: 'plans', ing: 'planning', type: 'regular', meaning: 'To decide on a future course of action' },
  play: { base: 'play', v2: 'played', v3: 'played', s: 'plays', ing: 'playing', type: 'regular', meaning: 'To engage in activity for enjoyment' },
  point: { base: 'point', v2: 'pointed', v3: 'pointed', s: 'points', ing: 'pointing', type: 'regular', meaning: 'To direct attention towards something' },
  polish: { base: 'polish', v2: 'polished', v3: 'polished', s: 'polishes', ing: 'polishing', type: 'regular', meaning: 'To make smooth and shiny' },
  post: { base: 'post', v2: 'posted', v3: 'posted', s: 'posts', ing: 'posting', type: 'regular', meaning: 'To send mail or publish online' },
  pour: { base: 'pour', v2: 'poured', v3: 'poured', s: 'pours', ing: 'pouring', type: 'regular', meaning: 'To flow in a steady stream' },
  practise: { base: 'practise', v2: 'practised', v3: 'practised', s: 'practises', ing: 'practising', type: 'regular', meaning: 'To perform an activity repeatedly' },
  pray: { base: 'pray', v2: 'prayed', v3: 'prayed', s: 'prays', ing: 'playing', type: 'regular', meaning: 'To address a deity or hope' },
  prepare: { base: 'prepare', v2: 'prepared', v3: 'prepared', s: 'prepares', ing: 'preparing', type: 'regular', meaning: 'To get ready for something' },
  present: { base: 'present', v2: 'presented', v3: 'presented', s: 'presents', ing: 'presenting', type: 'regular', meaning: 'To show or offer something' },
  press: { base: 'press', v2: 'pressed', v3: 'pressed', s: 'presses', ing: 'pressing', type: 'regular', meaning: 'To apply weight or force' },
  prevent: { base: 'prevent', v2: 'prevented', v3: 'prevented', s: 'prevents', ing: 'preventing', type: 'regular', meaning: 'To stop something from happening' },
  produce: { base: 'produce', v2: 'produced', v3: 'produced', s: 'produces', ing: 'producing', type: 'regular', meaning: 'To make or manufacture' },
  promise: { base: 'promise', v2: 'promised', v3: 'promised', s: 'promises', ing: 'promising', type: 'regular', meaning: 'To state that one will definitely do something' },
  protect: { base: 'protect', v2: 'protected', v3: 'protected', s: 'protects', ing: 'protecting', type: 'regular', meaning: 'To keep safe from harm' },
  provide: { base: 'provide', v2: 'provided', v3: 'provided', s: 'provides', ing: 'providing', type: 'regular', meaning: 'To supply or make available' },
  pull: { base: 'pull', v2: 'pulled', v3: 'pulled', s: 'pulls', ing: 'pulling', type: 'regular', meaning: 'To exert force to move something towards one' },
  push: { base: 'push', v2: 'pushed', v3: 'pushed', s: 'pushes', ing: 'pushing', type: 'regular', meaning: 'To exert force to move something away' },
  question: { base: 'question', v2: 'questioned', v3: 'questioned', s: 'questions', ing: 'questioning', type: 'regular', meaning: 'To ask someone questions' },
  quit: { base: 'quit', v2: 'quitted', v3: 'quitted', s: 'quits', ing: 'quitting', type: 'regular', meaning: 'To stop doing something or leave a job' },
  rain: { base: 'rain', v2: 'rained', v3: 'rained', s: 'rains', ing: 'raining', type: 'regular', meaning: 'To fall from the clouds in drops' },
  raise: { base: 'raise', v2: 'raised', v3: 'raised', s: 'raises', ing: 'raising', type: 'regular', meaning: 'To lift or move to a higher position' },
  reach: { base: 'reach', v2: 'reached', v3: 'reached', s: 'reaches', ing: 'reaching', type: 'regular', meaning: 'To stretch out an arm or arrive at' },
  realise: { base: 'realise', v2: 'realised', v3: 'realised', s: 'realises', ing: 'realising', type: 'regular', meaning: 'To become fully aware of' },
  receive: { base: 'receive', v2: 'received', v3: 'received', s: 'receives', ing: 'receiving', type: 'regular', meaning: 'To be given or get something' },
  recognise: { base: 'recognise', v2: 'recognised', v3: 'recognised', s: 'recognises', ing: 'recognising', type: 'regular', meaning: 'To identify from previous knowledge' },
  record: { base: 'record', v2: 'recorded', v3: 'recorded', s: 'records', ing: 'recording', type: 'regular', meaning: 'To set down in permanent form' },
  reduce: { base: 'reduce', v2: 'reduced', v3: 'reduced', s: 'reduces', ing: 'reducing', type: 'regular', meaning: 'To make smaller or less' },
  reflect: { base: 'reflect', v2: 'reflected', v3: 'reflected', s: 'reflects', ing: 'reflecting', type: 'regular', meaning: 'To throw back light or heat' },
  refuse: { base: 'refuse', v2: 'refused', v3: 'refused', s: 'refuses', ing: 'refusing', type: 'regular', meaning: 'To indicate unwillingness to do something' },
  regard: { base: 'regard', v2: 'call/see', v3: 'regarded', s: 'regards', ing: 'regarding', type: 'regular', meaning: 'To consider in a specified way' },
  relax: { base: 'relax', v2: 'relaxed', v3: 'relaxed', s: 'relaxes', ing: 'relaxing', type: 'regular', meaning: 'To rest from work or effort' },
  remain: { base: 'remain', v2: 'remained', v3: 'remained', s: 'remains', ing: 'remaining', type: 'regular', meaning: 'To continue to exist or stay' },
  remember: { base: 'remember', v2: 'remembered', v3: 'remembered', s: 'remembers', ing: 'remembering', type: 'regular', meaning: 'To recall to mind' },
  remind: { base: 'remind', v2: 'reminded', v3: 'reminded', s: 'reminds', ing: 'reminding', type: 'regular', meaning: 'To cause someone to remember' },
  remove: { base: 'remove', v2: 'removed', v3: 'removed', s: 'removes', ing: 'removing', type: 'regular', meaning: 'To take something away' },
  repair: { base: 'repair', v2: 'repaired', v3: 'repaired', s: 'repairs', ing: 'repairing', type: 'regular', meaning: 'To fix something that is broken' },
  repeat: { base: 'repeat', v2: 'repeated', v3: 'repeated', s: 'repeats', ing: 'repeating', type: 'regular', meaning: 'To say or do something again' },
  replace: { base: 'replace', v2: 'replaced', v3: 'replaced', s: 'replaces', ing: 'replacing', type: 'regular', meaning: 'To provide a substitute' },
  reply: { base: 'reply', v2: 'replied', v3: 'replied', s: 'replies', ing: 'replying', type: 'regular', meaning: 'To answer or respond' },
  report: { base: 'report', v2: 'reported', v3: 'reported', s: 'reports', ing: 'reporting', type: 'regular', meaning: 'To give a spoken or written account' },
  request: { base: 'request', v2: 'requested', v3: 'requested', s: 'requests', ing: 'requesting', type: 'regular', meaning: 'To ask for something formally' },
  rescue: { base: 'rescue', v2: 'rescued', v3: 'rescued', s: 'rescues', ing: 'rescuing', type: 'regular', meaning: 'To save from danger' },
  return: { base: 'return', v2: 'returned', v3: 'returned', s: 'returns', ing: 'returning', type: 'regular', meaning: 'To come or go back' },
  reveal: { base: 'reveal', v2: 'revealed', v3: 'revealed', s: 'reveals', ing: 'revealing', type: 'regular', meaning: 'To make something known' },
  save: { base: 'save', v2: 'saved', v3: 'saved', s: 'saves', ing: 'saving', type: 'regular', meaning: 'To rescue or keep safe' },
  search: { base: 'search', v2: 'searched', v3: 'searched', s: 'searches', ing: 'searching', type: 'regular', meaning: 'To look for something carefully' },
  serve: { base: 'serve', v2: 'served', v3: 'served', s: 'serves', ing: 'serving', type: 'regular', meaning: 'To perform duties or provide food' },
  settle: { base: 'settle', v2: 'settled', v3: 'settled', s: 'settles', ing: 'settling', type: 'regular', meaning: 'To resolve or reach an agreement' },
  share: { base: 'share', v2: 'shared', v3: 'shared', s: 'shares', ing: 'sharing', type: 'regular', meaning: 'To have a portion of something with others' },
  shout: { base: 'shout', v2: 'shouted', v3: 'shouted', s: 'shouts', ing: 'shouting', type: 'regular', meaning: 'To cry out loudly' },
  sign: { base: 'sign', v2: 'signed', v3: 'signed', s: 'signs', ing: 'signing', type: 'regular', meaning: 'To write one\'s name for authorization' },
  smile: { base: 'smile', v2: 'smiled', v3: 'smiled', s: 'smiles', ing: 'smiling', type: 'regular', meaning: 'To form the mouth into an expression of joy' },
  sound: { base: 'sound', v2: 'sounded', v3: 'sounded', s: 'sounds', ing: 'sounding', type: 'regular', meaning: 'To emit a noise' },
  start: { base: 'start', v2: 'started', v3: 'started', s: 'starts', ing: 'starting', type: 'regular', meaning: 'To begin doing something' },
  stay: { base: 'stay', v2: 'stayed', v3: 'stayed', s: 'stays', ing: 'staying', type: 'regular', meaning: 'To remain in the same place' },
  stop: { base: 'stop', v2: 'stopped', v3: 'stopped', s: 'stops', ing: 'stopping', type: 'regular', meaning: 'To cease moving or doing' },
  study: { base: 'study', v2: 'studied', v3: 'studied', s: 'studies', ing: 'studying', type: 'regular', meaning: 'To devote time to learning' },
  suggest: { base: 'suggest', v2: 'suggested', v3: 'suggested', s: 'suggests', ing: 'suggesting', type: 'regular', meaning: 'To put forward for consideration' },
  support: { base: 'support', v2: 'supported', v3: 'supported', s: 'supports', ing: 'supporting', type: 'regular', meaning: 'To give assistance or bear weight' },
  suppose: { base: 'suppose', v2: 'supposed', v3: 'supposed', s: 'supposes', ing: 'supposing', type: 'regular', meaning: 'To assume or think' },
  surprise: { base: 'surprise', v2: 'surprised', v3: 'surprised', s: 'surprises', ing: 'surprising', type: 'regular', meaning: 'To cause wonder or astonishment' },
  talk: { base: 'talk', v2: 'talked', v3: 'talked', s: 'talks', ing: 'talking', type: 'regular', meaning: 'To speak in order to give information' },
  thank: { base: 'thank', v2: 'thanked', v3: 'thanked', s: 'thanks', ing: 'thanking', type: 'regular', meaning: 'To express gratitude' },
  touch: { base: 'touch', v2: 'touched', v3: 'touched', s: 'touches', ing: 'touching', type: 'regular', meaning: 'To come into contact with' },
  train: { base: 'train', v2: 'trained', v3: 'trained', s: 'trains', ing: 'training', type: 'regular', meaning: 'To teach a particular skill or type of behavior' },
  travel: { base: 'travel', v2: 'travelled', v3: 'travelled', s: 'travels', ing: 'travelling', type: 'regular', meaning: 'To go on a journey' },
  treat: { base: 'treat', v2: 'treated', v3: 'treated', s: 'treats', ing: 'treating', type: 'regular', meaning: 'To behave towards or deal with' },
  trust: { base: 'trust', v2: 'trusted', v3: 'trusted', s: 'trusts', ing: 'trusting', type: 'regular', meaning: 'To believe in the reliability of' },
  try: { base: 'try', v2: 'tried', v3: 'tried', s: 'tries', ing: 'trying', type: 'regular', meaning: 'To make an attempt' },
  turn: { base: 'turn', v2: 'turned', v3: 'turned', s: 'turns', ing: 'turning', type: 'regular', meaning: 'To move in a circular direction' },
  use: { base: 'use', v2: 'used', v3: 'used', s: 'uses', ing: 'using', type: 'regular', meaning: 'To take or hold something to accomplish a task' },
  visit: { base: 'visit', v2: 'visited', v3: 'visited', s: 'visits', ing: 'visiting', type: 'regular', meaning: 'To go to see someone or something' },
  wait: { base: 'wait', v2: 'waited', v3: 'waited', s: 'waits', ing: 'waiting', type: 'regular', meaning: 'To stay where one is until a time' },
  walk: { base: 'walk', v2: 'walked', v3: 'walked', s: 'walks', ing: 'walking', type: 'regular', meaning: 'To move at a regular pace on foot' },
  want: { base: 'want', v2: 'wanted', v3: 'wanted', s: 'wants', ing: 'wanting', type: 'regular', meaning: 'To have a desire to possess or do' },
  wash: { base: 'wash', v2: 'washed', v3: 'washed', s: 'washes', ing: 'washing', type: 'regular', meaning: 'To clean with water' },
  watch: { base: 'watch', v2: 'watched', v3: 'watched', s: 'watches', ing: 'watching', type: 'regular', meaning: 'To look at or observe attentively' },
  wet: { base: 'wet', v2: 'wetted', v3: 'wetted', s: 'wets', ing: 'wetting', type: 'regular', meaning: 'To cover with water' },
  wish: { base: 'wish', v2: 'wished', v3: 'wished', s: 'wishes', ing: 'wishing', type: 'regular', meaning: 'To feel or express a strong desire' },
  wonder: { base: 'wonder', v2: 'wondered', v3: 'wondered', s: 'wonders', ing: 'wondering', type: 'regular', meaning: 'To desire to know something' },
  work: { base: 'work', v2: 'worked', v3: 'worked', s: 'works', ing: 'working', type: 'regular', meaning: 'To engage in activity to achieve a result' },
  worry: { base: 'worry', v2: 'worried', v3: 'worried', s: 'worries', ing: 'worrying', type: 'regular', meaning: 'To feel anxious or troubled' },

  // ==========================================
  // TYPE 3: IRREGULAR VERBS (Shapeshifters)
  // ==========================================
  abide: { base: 'abide', v2: 'abode', v3: 'abode', s: 'abides', ing: 'abiding', type: 'irregular', meaning: 'To accept or act in accordance with a rule' },
  arise: { base: 'arise', v2: 'arose', v3: 'arisen', s: 'arises', ing: 'arising', type: 'irregular', meaning: 'To emerge or become apparent' },
  awake: { base: 'awake', v2: 'awoke', v3: 'awoken', s: 'awakes', ing: 'awaking', type: 'irregular', meaning: 'To stop sleeping' },
  be: { base: 'be', v2: 'was/were', v3: 'been', s: 'is', ing: 'being', type: 'irregular', meaning: 'To exist or occur' },
  bear: { base: 'bear', v2: 'bore', v3: 'born', s: 'bears', ing: 'bearing', type: 'irregular', meaning: 'To carry or support' },
  beat: { base: 'beat', v2: 'beat', v3: 'beaten', s: 'beats', ing: 'beating', type: 'irregular', meaning: 'To strike repeatedly' },
  become: { base: 'become', v2: 'became', v3: 'become', s: 'becomes', ing: 'becoming', type: 'irregular', meaning: 'To begin to be' },
  befall: { base: 'befall', v2: 'befell', v3: 'befallen', s: 'befalls', ing: 'befalling', type: 'irregular', meaning: 'To happen to someone' },
  begin: { base: 'begin', v2: 'began', v3: 'begun', s: 'begins', ing: 'beginning', type: 'irregular', meaning: 'To start something' },
  behold: { base: 'behold', v2: 'beheld', v3: 'beheld', s: 'beholds', ing: 'beholding', type: 'irregular', meaning: 'To see or observe' },
  bend: { base: 'bend', v2: 'bent', v3: 'bent', s: 'bends', ing: 'bending', type: 'irregular', meaning: 'To shape or force into a curve' },
  bereave: { base: 'bereave', v2: 'bereft', v3: 'bereft', s: 'bereaves', ing: 'bereaving', type: 'irregular', meaning: 'To deprive of a loved one' },
  beseech: { base: 'beseech', v2: 'besought', v3: 'besought', s: 'beseeches', ing: 'beseeching', type: 'irregular', meaning: 'To ask urgently and fervently' },
  bestride: { base: 'bestride', v2: 'bestrode', v3: 'bestridden', s: 'bestrides', ing: 'bestriding', type: 'irregular', meaning: 'To sit or stand with a leg on either side' },
  betake: { base: 'betake', v2: 'betook', v3: 'betaken', s: 'betakes', ing: 'betaking', type: 'irregular', meaning: 'To go to a place' },
  bethink: { base: 'bethink', v2: 'bethought', v3: 'bethought', s: 'bethinks', ing: 'bethinking', type: 'irregular', meaning: 'To come to think' },
  bind: { base: 'bind', v2: 'bound', v3: 'bound', s: 'binds', ing: 'binding', type: 'irregular', meaning: 'To tie or fasten tightly' },
  bite: { base: 'bite', v2: 'bit', v3: 'bitten', s: 'bites', ing: 'biting', type: 'irregular', meaning: 'To use teeth to cut into something' },
  bleed: { base: 'bleed', v2: 'bled', v3: 'bled', s: 'bleeds', ing: 'bleeding', type: 'irregular', meaning: 'To lose blood' },
  blow: { base: 'blow', v2: 'blew', v3: 'blown', s: 'blows', ing: 'blowing', type: 'irregular', meaning: 'To expel air' },
  break: { base: 'break', v2: 'broke', v3: 'broken', s: 'breaks', ing: 'breaking', type: 'irregular', meaning: 'To separate into pieces suddenly' },
  breed: { base: 'breed', v2: 'bred', v3: 'bred', s: 'breeds', ing: 'breeding', type: 'irregular', meaning: 'To produce offspring' },
  bring: { base: 'bring', v2: 'brought', v3: 'brought', s: 'brings', ing: 'bringing', type: 'irregular', meaning: 'To take or carry to a place' },
  browbeat: { base: 'browbeat', v2: 'browbeat', v3: 'browbeaten', s: 'browbeats', ing: 'browbeating', type: 'irregular', meaning: 'To intimidate someone' },
  build: { base: 'build', v2: 'built', v3: 'built', s: 'builds', ing: 'building', type: 'irregular', meaning: 'To construct something' },
  burn: { base: 'burn', v2: 'burnt', v3: 'burnt', s: 'burns', ing: 'burning', type: 'irregular', meaning: 'To be consumed by fire' },
  buy: { base: 'buy', v2: 'bought', v3: 'bought', s: 'buys', ing: 'buying', type: 'irregular', meaning: 'To obtain in exchange for payment' },
  catch: { base: 'catch', v2: 'caught', v3: 'caught', s: 'catches', ing: 'catching', type: 'irregular', meaning: 'To intercept and hold' },
  choose: { base: 'choose', v2: 'chose', v3: 'chosen', s: 'chooses', ing: 'choosing', type: 'irregular', meaning: 'To pick out from alternatives' },
  cleave: { base: 'cleave', v2: 'clove', v3: 'cloven', s: 'cleaves', ing: 'cleaving', type: 'irregular', meaning: 'To split or sever something' },
  cling: { base: 'cling', v2: 'clung', v3: 'clung', s: 'clings', ing: 'clinging', type: 'irregular', meaning: 'To hold on tightly' },
  come: { base: 'come', v2: 'came', v3: 'come', s: 'comes', ing: 'coming', type: 'irregular', meaning: 'To move or travel towards the speaker' },
  creep: { base: 'creep', v2: 'crept', v3: 'crept', s: 'creeps', ing: 'creeping', type: 'irregular', meaning: 'To move slowly and carefully' },
  deal: { base: 'deal', v2: 'dealt', v3: 'dealt', s: 'deals', ing: 'dealing', type: 'irregular', meaning: 'To distribute or take action' },
  dig: { base: 'dig', v2: 'dug', v3: 'dug', s: 'digs', ing: 'digging', type: 'irregular', meaning: 'To break up and move earth' },
  do: { base: 'do', v2: 'did', v3: 'done', s: 'does', ing: 'doing', type: 'irregular', meaning: 'To perform an action' },
  draw: { base: 'draw', v2: 'drew', v3: 'drawn', s: 'draws', ing: 'drawing', type: 'irregular', meaning: 'To produce a picture or pull something' },
  dream: { base: 'dream', v2: 'dreamt', v3: 'dreamt', s: 'dreams', ing: 'dreaming', type: 'irregular', meaning: 'To experience images during sleep' },
  drink: { base: 'drink', v2: 'drank', v3: 'drunk', s: 'drinks', ing: 'drinking', type: 'irregular', meaning: 'To swallow liquid' },
  drive: { base: 'drive', v2: 'drove', v3: 'driven', s: 'drives', ing: 'driving', type: 'irregular', meaning: 'To operate a vehicle' },
  dwell: { base: 'dwell', v2: 'dwelt', v3: 'dwelt', s: 'dwells', ing: 'dwelling', type: 'irregular', meaning: 'To live in or at a specified place' },
  eat: { base: 'eat', v2: 'ate', v3: 'eaten', s: 'eats', ing: 'eating', type: 'irregular', meaning: 'To consume food' },
  fall: { base: 'fall', v2: 'fell', v3: 'fallen', s: 'falls', ing: 'falling', type: 'irregular', meaning: 'To drop downwards' },
  feed: { base: 'feed', v2: 'fed', v3: 'fed', s: 'feeds', ing: 'feeding', type: 'irregular', meaning: 'To give food to' },
  feel: { base: 'feel', v2: 'felt', v3: 'felt', s: 'feels', ing: 'feeling', type: 'irregular', meaning: 'To experience an emotion or sensation' },
  fight: { base: 'fight', v2: 'fought', v3: 'fought', s: 'fights', ing: 'fighting', type: 'irregular', meaning: 'To engage in conflict' },
  find: { base: 'find', v2: 'found', v3: 'found', s: 'finds', ing: 'finding', type: 'irregular', meaning: 'To discover something' },
  flee: { base: 'flee', v2: 'fled', v3: 'fled', s: 'flees', ing: 'fleeing', type: 'irregular', meaning: 'To run away from danger' },
  fling: { base: 'fling', v2: 'flung', v3: 'flung', s: 'flings', ing: 'flinging', type: 'irregular', meaning: 'To throw forcefully' },
  fly: { base: 'fly', v2: 'flew', v3: 'flown', s: 'flies', ing: 'flying', type: 'irregular', meaning: 'To move through the air' },
  forbid: { base: 'forbid', v2: 'forbade', v3: 'forbidden', s: 'forbids', ing: 'forbidding', type: 'irregular', meaning: 'To order not to do something' },
  forego: { base: 'forego', v2: 'forewent', v3: 'foregone', s: 'foregoes', ing: 'foregoing', type: 'irregular', meaning: 'To precede in time or place' },
  foresee: { base: 'foresee', v2: 'foresaw', v3: 'foreseen', s: 'foresees', ing: 'foreseeing', type: 'irregular', meaning: 'To predict or be aware of in advance' },
  foretell: { base: 'foretell', v2: 'foretold', v3: 'foretold', s: 'foretells', ing: 'foretelling', type: 'irregular', meaning: 'To predict future events' },
  forget: { base: 'forget', v2: 'forgot', v3: 'forgotten', s: 'forgets', ing: 'forgetting', type: 'irregular', meaning: 'To fail to remember' },
  forgive: { base: 'forgive', v2: 'forgave', v3: 'forgiven', s: 'forgives', ing: 'forgiving', type: 'irregular', meaning: 'To stop feeling angry or resentful towards someone' },
  forgo: { base: 'forgo', v2: 'forwent', v3: 'forgone', s: 'forgoes', ing: 'forgoing', type: 'irregular', meaning: 'To go without something' },
  forsake: { base: 'forsake', v2: 'forsook', v3: 'forsaken', s: 'forsakes', ing: 'forsaking', type: 'irregular', meaning: 'To abandon or give up' },
  forswear: { base: 'forswear', v2: 'forswore', v3: 'forsworn', s: 'forswears', ing: 'forswearing', type: 'irregular', meaning: 'To agree to give up or reject' },
  freeze: { base: 'freeze', v2: 'froze', v3: 'frozen', s: 'freezes', ing: 'freezing', type: 'irregular', meaning: 'To turn into ice' },
  gainsay: { base: 'gainsay', v2: 'gainsaid', v3: 'gainsaid', s: 'gainsays', ing: 'gainsaying', type: 'irregular', meaning: 'To deny or contradict' },
  get: { base: 'get', v2: 'got', v3: 'got', s: 'gets', ing: 'getting', type: 'irregular', meaning: 'To receive or obtain' },
  gird: { base: 'gird', v2: 'girt', v3: 'girt', s: 'girds', ing: 'girding', type: 'irregular', meaning: 'To encircle or secure with a belt' },
  give: { base: 'give', v2: 'gave', v3: 'given', s: 'gives', ing: 'giving', type: 'irregular', meaning: 'To transfer possession freely' },
  go: { base: 'go', v2: 'went', v3: 'gone', s: 'goes', ing: 'going', type: 'irregular', meaning: 'To move from one place to another' },
  grind: { base: 'grind', v2: 'ground', v3: 'ground', s: 'grinds', ing: 'grinding', type: 'irregular', meaning: 'To reduce to small particles' },
  grow: { base: 'grow', v2: 'grew', v3: 'grown', s: 'grows', ing: 'growing', type: 'irregular', meaning: 'To increase in size' },
  hamstring: { base: 'hamstring', v2: 'hamstrung', v3: 'hamstrung', s: 'hamstrings', ing: 'hamstringing', type: 'irregular', meaning: 'To cripple or disable' },
  hang: { base: 'hang', v2: 'hung', v3: 'hung', s: 'hangs', ing: 'hanging', type: 'irregular', meaning: 'To suspend from above' },
  have: { base: 'have', v2: 'had', v3: 'had', s: 'has', ing: 'having', type: 'irregular', meaning: 'To possess or own' },
  hear: { base: 'hear', v2: 'heard', v3: 'heard', s: 'hears', ing: 'hearing', type: 'irregular', meaning: 'To perceive sound' },
  hide: { base: 'hide', v2: 'hid', v3: 'hidden', s: 'hides', ing: 'hiding', type: 'irregular', meaning: 'To put out of sight' },
  hold: { base: 'hold', v2: 'held', v3: 'held', s: 'holds', ing: 'holding', type: 'irregular', meaning: 'To grasp or carry' },
  inlay: { base: 'inlay', v2: 'inlaid', v3: 'inlaid', s: 'inlays', ing: 'inlaying', type: 'irregular', meaning: 'To ornament an object with patterns' },
  interweave: { base: 'interweave', v2: 'interwove', v3: 'interwoven', s: 'interweaves', ing: 'interweaving', type: 'irregular', meaning: 'To weave together' },
  keep: { base: 'keep', v2: 'kept', v3: 'kept', s: 'keeps', ing: 'keeping', type: 'irregular', meaning: 'To retain possession of' },
  kneel: { base: 'kneel', v2: 'knelt', v3: 'knelt', s: 'kneels', ing: 'kneeling', type: 'irregular', meaning: 'To go down on knees' },
  know: { base: 'know', v2: 'knew', v3: 'known', s: 'knows', ing: 'knowing', type: 'irregular', meaning: 'To be aware of through observation' },
  lay: { base: 'lay', v2: 'laid', v3: 'laid', s: 'lays', ing: 'laying', type: 'irregular', meaning: 'To put something down gently' },
  lead: { base: 'lead', v2: 'led', v3: 'led', s: 'leads', ing: 'leading', type: 'irregular', meaning: 'To show the way' },
  lean: { base: 'lean', v2: 'leant', v3: 'leant', s: 'leans', ing: 'leaning', type: 'irregular', meaning: 'To be in or move into a sloping position' },
  leap: { base: 'leap', v2: 'leapt', v3: 'leapt', s: 'leaps', ing: 'leaping', type: 'irregular', meaning: 'To jump high or far' },
  learn: { base: 'learn', v2: 'learnt', v3: 'learnt', s: 'learns', ing: 'learning', type: 'irregular', meaning: 'To gain knowledge or skill' },
  leave: { base: 'leave', v2: 'left', v3: 'left', s: 'leaves', ing: 'leaving', type: 'irregular', meaning: 'To go away from' },
  lend: { base: 'lend', v2: 'lent', v3: 'lent', s: 'lends', ing: 'lending', type: 'irregular', meaning: 'To allow usage temporarily' },
  lie: { base: 'lie', v2: 'lay', v3: 'lain', s: 'lies', ing: 'lying', type: 'irregular', meaning: 'To be in a horizontal position' },
  light: { base: 'light', v2: 'lit', v3: 'lit', s: 'lights', ing: 'lighting', type: 'irregular', meaning: 'To provide with light or ignite' },
  lose: { base: 'lose', v2: 'lost', v3: 'lost', s: 'loses', ing: 'losing', type: 'irregular', meaning: 'To be deprived of something' },
  make: { base: 'make', v2: 'made', v3: 'made', s: 'makes', ing: 'making', type: 'irregular', meaning: 'To form or create' },
  mean: { base: 'mean', v2: 'meant', v3: 'meant', s: 'means', ing: 'meaning', type: 'irregular', meaning: 'To intend to convey' },
  meet: { base: 'meet', v2: 'met', v3: 'met', s: 'meets', ing: 'meeting', type: 'irregular', meaning: 'To come into the presence of' },
  mistake: { base: 'mistake', v2: 'mistook', v3: 'mistaken', s: 'mistakes', ing: 'mistaking', type: 'irregular', meaning: 'To understand or judge incorrectly' },
  misspell: { base: 'misspell', v2: 'misspelt', v3: 'misspelt', s: 'misspells', ing: 'misspelling', type: 'irregular', meaning: 'To spell a word incorrectly' },
  misspend: { base: 'misspend', v2: 'misspent', v3: 'misspent', s: 'misspends', ing: 'misspending', type: 'irregular', meaning: 'To spend money foolishly' },
  misunderstand: { base: 'misunderstand', v2: 'misunderstood', v3: 'misunderstood', s: 'misunderstands', ing: 'misunderstanding', type: 'irregular', meaning: 'To fail to understand' },
  outdo: { base: 'outdo', v2: 'outdid', v3: 'outdone', s: 'outdoes', ing: 'outdoing', type: 'irregular', meaning: 'To perform better than others' },
  outfight: { base: 'outfight', v2: 'outfought', v3: 'outfought', s: 'outfights', ing: 'outfighting', type: 'irregular', meaning: 'To fight better than' },
  outgo: { base: 'outgo', v2: 'outwent', v3: 'outgone', s: 'outgoes', ing: 'outgoing', type: 'irregular', meaning: 'To go beyond or surpass' },
  outgrow: { base: 'outgrow', v2: 'outgrew', v3: 'outgrown', s: 'outgrows', ing: 'outgrowing', type: 'irregular', meaning: 'To grow too large for' },
  outride: { base: 'outride', v2: 'outrode', v3: 'outridden', s: 'outrides', ing: 'outriding', type: 'irregular', meaning: 'To ride better or faster than' },
  outrun: { base: 'outrun', v2: 'outran', v3: 'outrun', s: 'outruns', ing: 'outrunning', type: 'irregular', meaning: 'To run faster than' },
  outsell: { base: 'outsell', v2: 'outsold', v3: 'outsold', s: 'outsells', ing: 'outselling', type: 'irregular', meaning: 'To sell more than others' },
  outshine: { base: 'outshine', v2: 'outshone', v3: 'outshone', s: 'outshines', ing: 'outshining', type: 'irregular', meaning: 'To shine more brightly than' },
  outspeak: { base: 'outspeak', v2: 'outspeak', v3: 'outspoken', s: 'outspeaks', ing: 'outspeaking', type: 'irregular', meaning: 'To speak more than others' },
  outswim: { base: 'outswim', v2: 'outswam', v3: 'outswum', s: 'outswims', ing: 'outswimming', type: 'irregular', meaning: 'To swim faster than' },
  outthink: { base: 'outthink', v2: 'outthought', v3: 'outthought', s: 'outthinks', ing: 'outthinking', type: 'irregular', meaning: 'To think better or faster than' },
  outwear: { base: 'outwear', v2: 'outwore', v3: 'outworn', s: 'outwears', ing: 'outwearing', type: 'irregular', meaning: 'To last longer than' },
  outwrite: { base: 'outwrite', v2: 'outwrote', v3: 'outwritten', s: 'outwrites', ing: 'outwriting', type: 'irregular', meaning: 'To write more or better than' },
  overbear: { base: 'overbear', v2: 'overbore', v3: 'overborne', s: 'overbears', ing: 'overbearing', type: 'irregular', meaning: 'To overcome by physical force' },
  overcome: { base: 'overcome', v2: 'overcame', v3: 'overcome', s: 'overcomes', ing: 'overcoming', type: 'irregular', meaning: 'To succeed in dealing with' },
  overdo: { base: 'overdo', v2: 'overdid', v3: 'overdone', s: 'overdoes', ing: 'overdoing', type: 'irregular', meaning: 'To do something to excess' },
  overdraw: { base: 'overdraw', v2: 'overdrew', v3: 'overdrawn', s: 'overdraws', ing: 'overdrawing', type: 'irregular', meaning: 'To draw more money than is in the account' },
  overeat: { base: 'overeat', v2: 'overeat', v3: 'overeaten', s: 'overeats', ing: 'overeating', type: 'irregular', meaning: 'To eat too much' },
  overfly: { base: 'overfly', v2: 'overflew', v3: 'overflown', s: 'overflies', ing: 'overflying', type: 'irregular', meaning: 'To fly over' },
  overhang: { base: 'overhang', v2: 'overhung', v3: 'overhung', s: 'overhangs', ing: 'overhanging', type: 'irregular', meaning: 'To hang or extend over' },
  overhear: { base: 'overhear', v2: 'overheard', v3: 'overheard', s: 'overhears', ing: 'overhearing', type: 'irregular', meaning: 'To hear without the speaker\'s knowledge' },
  overlay: { base: 'overlay', v2: 'overlaid', v3: 'overlaid', s: 'overlays', ing: 'overlaying', type: 'irregular', meaning: 'To cover the surface with a coating' },
  overleap: { base: 'overleap', v2: 'overleapt', v3: 'overleapt', s: 'overleaps', ing: 'overleaping', type: 'irregular', meaning: 'To leap over' },
  overlie: { base: 'overlie', v2: 'overlay', v3: 'overlain', s: 'overlies', ing: 'overlying', type: 'irregular', meaning: 'To lie on top of' },
  overpay: { base: 'overpay', v2: 'overpaid', v3: 'overpaid', s: 'overpays', ing: 'overpaying', type: 'irregular', meaning: 'To pay too much' },
  override: { base: 'override', v2: 'overrode', v3: 'overridden', s: 'overrides', ing: 'overriding', type: 'irregular', meaning: 'To use one\'s authority to reject' },
  overrun: { base: 'overrun', v2: 'overran', v3: 'overrun', s: 'overruns', ing: 'overrunning', type: 'irregular', meaning: 'To occupy or spread over' },
  oversee: { base: 'oversee', v2: 'oversaw', v3: 'overseen', s: 'oversees', ing: 'overseeing', type: 'irregular', meaning: 'To supervise a person or work' },
  oversleep: { base: 'oversleep', v2: 'overslept', v3: 'overslept', s: 'oversleeps', ing: 'oversleeping', type: 'irregular', meaning: 'To sleep longer than intended' },
  overtake: { base: 'overtake', v2: 'overtook', v3: 'overtaken', s: 'overtakes', ing: 'overtaking', type: 'irregular', meaning: 'To catch up with and pass' },
  overthink: { base: 'overthink', v2: 'overthought', v3: 'overthought', s: 'overthinks', ing: 'overthinking', type: 'irregular', meaning: 'To think about something too much' },
  overthrow: { base: 'overthrow', v2: 'overthrew', v3: 'overthrown', s: 'overthrows', ing: 'overthrowing', type: 'irregular', meaning: 'To remove from power' },
  overwind: { base: 'overwind', v2: 'overwound', v3: 'overwound', s: 'overwinds', ing: 'overwinding', type: 'irregular', meaning: 'To wind something too far' },
  overwrite: { base: 'overwrite', v2: 'overwrote', v3: 'overwritten', s: 'overwrites', ing: 'overwriting', type: 'irregular', meaning: 'To write over' },
  partake: { base: 'partake', v2: 'partook', v3: 'partaken', s: 'partakes', ing: 'partaking', type: 'irregular', meaning: 'To join in an activity' },
  pay: { base: 'pay', v2: 'paid', v3: 'paid', s: 'pays', ing: 'paying', type: 'irregular', meaning: 'To give money for goods/services' },
  plead: { base: 'plead', v2: 'pled', v3: 'pled', s: 'pleads', ing: 'pleading', type: 'irregular', meaning: 'To make an emotional appeal' },
  prove: { base: 'prove', v2: 'proved', v3: 'proved', s: 'proves', ing: 'proving', type: 'irregular', meaning: 'To demonstrate the truth or existence of something' },
  rebuild: { base: 'rebuild', v2: 'rebuilt', v3: 'rebuilt', s: 'rebuilds', ing: 'rebuilding', type: 'irregular', meaning: 'To build something again' },
  redo: { base: 'redo', v2: 'redid', v3: 'redone', s: 'redoes', ing: 'redoing', type: 'irregular', meaning: 'To do something again' },
  relay: { base: 'relay', v2: 'relaid', v3: 'relaid', s: 'relays', ing: 'relaying', type: 'irregular', meaning: 'To pass along a signal or message' },
  remake: { base: 'remake', v2: 'remade', v3: 'remade', s: 'remakes', ing: 'remaking', type: 'irregular', meaning: 'To make something again' },
  rend: { base: 'rend', v2: 'rent', v3: 'rent', s: 'rends', ing: 'rending', type: 'irregular', meaning: 'To tear something into pieces' },
  repay: { base: 'repay', v2: 'repaid', v3: 'repaid', s: 'repays', ing: 'repaying', type: 'irregular', meaning: 'To pay back money' },
  rerun: { base: 'rerun', v2: 'reran', v3: 'rerun', s: 'reruns', ing: 'rerunning', type: 'irregular', meaning: 'To run or broadcast again' },
  resell: { base: 'resell', v2: 'resold', v3: 'resold', s: 'resells', ing: 'reselling', type: 'irregular', meaning: 'To sell something again' },
  resend: { base: 'resend', v2: 'resent', v3: 'resent', s: 'resends', ing: 'resending', type: 'irregular', meaning: 'To send something again' },
  rethink: { base: 'rethink', v2: 'rethought', v3: 'rethought', s: 'rethinks', ing: 'rethinking', type: 'irregular', meaning: 'To think about something again' },
  retread: { base: 'retread', v2: 'retrod', v3: 'retrod', s: 'retreads', ing: 'retreading', type: 'irregular', meaning: 'To tread again' },
  rewrite: { base: 'rewrite', v2: 'rewrote', v3: 'rewritten', s: 'rewrites', ing: 'rewriting', type: 'irregular', meaning: 'To write something again' },
  ride: { base: 'ride', v2: 'rode', v3: 'ridden', s: 'rides', ing: 'riding', type: 'irregular', meaning: 'To sit on and control a vehicle/animal' },
  ring: { base: 'ring', v2: 'rang', v3: 'rung', s: 'rings', ing: 'ringing', type: 'irregular', meaning: 'To make a clear resonant sound' },
  rise: { base: 'rise', v2: 'rose', v3: 'risen', s: 'rises', ing: 'rising', type: 'irregular', meaning: 'To move upwards' },
  run: { base: 'run', v2: 'ran', v3: 'run', s: 'runs', ing: 'running', type: 'irregular', meaning: 'To move faster than walking' },
  say: { base: 'say', v2: 'said', v3: 'said', s: 'says', ing: 'saying', type: 'irregular', meaning: 'To utter words' },
  see: { base: 'see', v2: 'saw', v3: 'seen', s: 'sees', ing: 'seeing', type: 'irregular', meaning: 'To perceive with the eyes' },
  seek: { base: 'seek', v2: 'sought', v3: 'sought', s: 'seeks', ing: 'seeking', type: 'irregular', meaning: 'To attempt to find' },
  sell: { base: 'sell', v2: 'sold', v3: 'sold', s: 'sells', ing: 'selling', type: 'irregular', meaning: 'To exchange goods for money' },
  send: { base: 'send', v2: 'sent', v3: 'sent', s: 'sends', ing: 'sending', type: 'irregular', meaning: 'To cause to go to a place' },
  shake: { base: 'shake', v2: 'shook', v3: 'shaken', s: 'shakes', ing: 'shaking', type: 'irregular', meaning: 'To move quickly back and forth' },
  shine: { base: 'shine', v2: 'shone', v3: 'shone', s: 'shines', ing: 'shining', type: 'irregular', meaning: 'To emit light' },
  shoe: { base: 'shoe', v2: 'shod', v3: 'shod', s: 'shoes', ing: 'shoeing', type: 'irregular', meaning: 'To fit a horse with shoes' },
  shoot: { base: 'shoot', v2: 'shot', v3: 'shot', s: 'shoots', ing: 'shooting', type: 'irregular', meaning: 'To fire a gun or weapon' },
  show: { base: 'show', v2: 'showed', v3: 'shown', s: 'shows', ing: 'showing', type: 'irregular', meaning: 'To allow to be seen' },
  shrive: { base: 'shrive', v2: 'shrove', v3: 'shriven', s: 'shrives', ing: 'shriving', type: 'irregular', meaning: 'To hear a confession' },
  shrink: { base: 'shrink', v2: 'shrank', v3: 'shrunk', s: 'shrinks', ing: 'shrinking', type: 'irregular', meaning: 'To become smaller' },
  sightsee: { base: 'sightsee', v2: 'sightsaw', v3: 'sightseen', s: 'sightsees', ing: 'sightseeing', type: 'irregular', meaning: 'To visit tourist attractions' },
  sing: { base: 'sing', v2: 'sang', v3: 'sung', s: 'sings', ing: 'singing', type: 'irregular', meaning: 'To make musical sounds with voice' },
  sink: { base: 'sink', v2: 'sank', v3: 'sunk', s: 'sinks', ing: 'sinking', type: 'irregular', meaning: 'To go down below the surface' },
  sit: { base: 'sit', v2: 'sat', v3: 'sat', s: 'sits', ing: 'sitting', type: 'irregular', meaning: 'To be in a seated position' },
  slay: { base: 'slay', v2: 'slew', v3: 'slain', s: 'slays', ing: 'slaying', type: 'irregular', meaning: 'To kill in a violent way' },
  sleep: { base: 'sleep', v2: 'slept', v3: 'slept', s: 'sleeps', ing: 'sleeping', type: 'irregular', meaning: 'To rest in a state of unconsciousness' },
  slide: { base: 'slide', v2: 'slid', v3: 'slid', s: 'slides', ing: 'sliding', type: 'irregular', meaning: 'To move smoothly along a surface' },
  sling: { base: 'sling', v2: 'slung', v3: 'slung', s: 'slings', ing: 'slinging', type: 'irregular', meaning: 'To throw from a sling' },
  slink: { base: 'slink', v2: 'slunk', v3: 'slunk', s: 'slinks', ing: 'slinking', type: 'irregular', meaning: 'To move stealthily' },
  smell: { base: 'smell', v2: 'smelt', v3: 'smelt', s: 'smells', ing: 'smelling', type: 'irregular', meaning: 'To perceive the odor of something' },
  smite: { base: 'smite', v2: 'smote', v3: 'smitten', s: 'smites', ing: 'smiting', type: 'irregular', meaning: 'To strike with a firm blow' },
  sow: { base: 'sow', v2: 'sowed', v3: 'sown', s: 'sows', ing: 'sowing', type: 'irregular', meaning: 'To plant seeds' },
  speak: { base: 'speak', v2: 'spoke', v3: 'spoken', s: 'speaks', ing: 'speaking', type: 'irregular', meaning: 'To say something' },
  speed: { base: 'speed', v2: 'sped', v3: 'sped', s: 'speeds', ing: 'speeding', type: 'irregular', meaning: 'To move or go quickly' },
  spell: { base: 'spell', v2: 'spelt', v3: 'spelt', s: 'spells', ing: 'spelling', type: 'irregular', meaning: 'To form words from letters' },
  spend: { base: 'spend', v2: 'spent', v3: 'spent', s: 'spends', ing: 'spending', type: 'irregular', meaning: 'To pay out money or time' },
  spill: { base: 'spill', v2: 'spilt', v3: 'spilt', s: 'spills', ing: 'spilling', type: 'irregular', meaning: 'To allow liquid to flow over' },
  spin: { base: 'spin', v2: 'spun', v3: 'spun', s: 'spins', ing: 'spinning', type: 'irregular', meaning: 'To turn or whirl round quickly' },
  spit: { base: 'spit', v2: 'spat', v3: 'spat', s: 'spits', ing: 'spitting', type: 'irregular', meaning: 'To eject saliva' },
  spoil: { base: 'spoil', v2: 'spoilt', v3: 'spoilt', s: 'spoils', ing: 'spoiling', type: 'irregular', meaning: 'To diminish or destroy the quality of' },
  spring: { base: 'spring', v2: 'sprang', v3: 'sprung', s: 'springs', ing: 'springing', type: 'irregular', meaning: 'To jump suddenly' },
  stand: { base: 'stand', v2: 'stood', v3: 'stood', s: 'stands', ing: 'standing', type: 'irregular', meaning: 'To be in an upright position' },
  steal: { base: 'steal', v2: 'stole', v3: 'stolen', s: 'steals', ing: 'stealing', type: 'irregular', meaning: 'To take without permission' },
  stick: { base: 'stick', v2: 'stuck', v3: 'stuck', s: 'sticks', ing: 'sticking', type: 'irregular', meaning: 'To adhere or attach' },
  sting: { base: 'sting', v2: 'stung', v3: 'stung', s: 'stings', ing: 'stinging', type: 'irregular', meaning: 'To wound with a sting' },
  stink: { base: 'stink', v2: 'stank', v3: 'stunk', s: 'stinks', ing: 'stinking', type: 'irregular', meaning: 'To have a strong unpleasant smell' },
  strew: { base: 'strew', v2: 'strewed', v3: 'strewn', s: 'strews', ing: 'strewing', type: 'irregular', meaning: 'To scatter or spread untidily' },
  stride: { base: 'stride', v2: 'strode', v3: 'stridden', s: 'strides', ing: 'striding', type: 'irregular', meaning: 'To walk with long steps' },
  strike: { base: 'strike', v2: 'struck', v3: 'struck', s: 'strikes', ing: 'striking', type: 'irregular', meaning: 'To hit forcibly' },
  string: { base: 'string', v2: 'strung', v3: 'strung', s: 'strings', ing: 'stringing', type: 'irregular', meaning: 'To hang or tie things with a string' },
  strive: { base: 'strive', v2: 'strove', v3: 'striven', s: 'strives', ing: 'striving', type: 'irregular', meaning: 'To make great efforts' },
  swell: { base: 'swell', v2: 'swelled', v3: 'swollen', s: 'swells', ing: 'swelling', type: 'irregular', meaning: 'To become larger in size' },
  swear: { base: 'swear', v2: 'swore', v3: 'sworn', s: 'swears', ing: 'swearing', type: 'irregular', meaning: 'To state on oath or curse' },
  sweep: { base: 'sweep', v2: 'swept', v3: 'swept', s: 'sweeps', ing: 'sweeping', type: 'irregular', meaning: 'To clean with a broom' },
  swim: { base: 'swim', v2: 'swam', v3: 'swum', s: 'swims', ing: 'swimming', type: 'irregular', meaning: 'To move through water' },
  swing: { base: 'swing', v2: 'swung', v3: 'swung', s: 'swings', ing: 'swinging', type: 'irregular', meaning: 'To move back and forth' },
  take: { base: 'take', v2: 'took', v3: 'taken', s: 'takes', ing: 'taking', type: 'irregular', meaning: 'To get hold of' },
  teach: { base: 'teach', v2: 'taught', v3: 'taught', s: 'teaches', ing: 'teaching', type: 'irregular', meaning: 'To instruct or educate' },
  tear: { base: 'tear', v2: 'tore', v3: 'torn', s: 'tears', ing: 'tearing', type: 'irregular', meaning: 'To pull apart force' },
  tell: { base: 'tell', v2: 'told', v3: 'told', s: 'tells', ing: 'telling', type: 'irregular', meaning: 'To communicate information' },
  think: { base: 'think', v2: 'thought', v3: 'thought', s: 'thinks', ing: 'thinking', type: 'irregular', meaning: 'To use the mind to consider' },
  throw: { base: 'throw', v2: 'threw', v3: 'thrown', s: 'throws', ing: 'throwing', type: 'irregular', meaning: 'To propel with force' },
  tread: { base: 'tread', v2: 'trod', v3: 'trodden', s: 'treads', ing: 'treading', type: 'irregular', meaning: 'To walk on' },
  unbend: { base: 'unbend', v2: 'unbent', v3: 'unbent', s: 'unbends', ing: 'unbending', type: 'irregular', meaning: 'To make straight' },
  unbind: { base: 'unbind', v2: 'unbound', v3: 'unbound', s: 'unbinds', ing: 'unbinding', type: 'irregular', meaning: 'To release from ties' },
  unclothe: { base: 'unclothe', v2: 'unclad', v3: 'unclad', s: 'unclothes', ing: 'unclothing', type: 'irregular', meaning: 'To remove clothes' },
  underbuy: { base: 'underbuy', v2: 'underbought', v3: 'underbought', s: 'underbuys', ing: 'underbuying', type: 'irregular', meaning: 'To buy for less' },
  underfeed: { base: 'underfeed', v2: 'underfed', v3: 'underfed', s: 'underfeeds', ing: 'underfeeding', type: 'irregular', meaning: 'To feed too little' },
  undergo: { base: 'undergo', v2: 'underwent', v3: 'undergone', s: 'undergoes', ing: 'undergoing', type: 'irregular', meaning: 'To experience something' },
  underlie: { base: 'underlie', v2: 'underlay', v3: 'underlain', s: 'underlies', ing: 'underlying', type: 'irregular', meaning: 'To be the cause or basis of' },
  underpay: { base: 'underpay', v2: 'underpaid', v3: 'underpaid', s: 'underpays', ing: 'underpaying', type: 'irregular', meaning: 'To pay too little' },
  underrun: { base: 'underrun', v2: 'underran', v3: 'underrun', s: 'underruns', ing: 'underrunning', type: 'irregular', meaning: 'To run under' },
  undersell: { base: 'undersell', v2: 'undersold', v3: 'undersold', s: 'undersells', ing: 'underselling', type: 'irregular', meaning: 'To sell for less' },
  undershoot: { base: 'undershoot', v2: 'undershot', v3: 'undershot', s: 'undershoots', ing: 'undershooting', type: 'irregular', meaning: 'To shoot short of the target' },
  understand: { base: 'understand', v2: 'understood', v3: 'understood', s: 'understands', ing: 'understanding', type: 'irregular', meaning: 'To comprehend meaning' },
  undertake: { base: 'undertake', v2: 'undertook', v3: 'undertaken', s: 'undertakes', ing: 'undertaking', type: 'irregular', meaning: 'To commit oneself to and begin' },
  underwrite: { base: 'underwrite', v2: 'underwrote', v3: 'underwritten', s: 'underwrites', ing: 'underwriting', type: 'irregular', meaning: 'To support financially' },
  undo: { base: 'undo', v2: 'undid', v3: 'undone', s: 'undoes', ing: 'undoing', type: 'irregular', meaning: 'To cancel or reverse' },
  undraw: { base: 'undraw', v2: 'undrew', v3: 'undrawn', s: 'undraws', ing: 'undrawing', type: 'irregular', meaning: 'To pull back a curtain' },
  unfreeze: { base: 'unfreeze', v2: 'unfroze', v3: 'unfrozen', s: 'unfreezes', ing: 'unfreezing', type: 'irregular', meaning: 'To thaw' },
  unhang: { base: 'unhang', v2: 'unhung', v3: 'unhung', s: 'unhangs', ing: 'unhanging', type: 'irregular', meaning: 'To take down from a hook' },
  unhide: { base: 'unhide', v2: 'unhid', v3: 'unhidden', s: 'unhides', ing: 'unhiding', type: 'irregular', meaning: 'To reveal what was hidden' },
  unhold: { base: 'unhold', v2: 'unheld', v3: 'unheld', s: 'unholds', ing: 'unholding', type: 'irregular', meaning: 'To release a grip' },
  unlearn: { base: 'unlearn', v2: 'unlearnt', v3: 'unlearnt', s: 'unlearns', ing: 'unlearning', type: 'irregular', meaning: 'To discard knowledge' },
  unmake: { base: 'unmake', v2: 'unmade', v3: 'unmade', s: 'unmakes', ing: 'unmaking', type: 'irregular', meaning: 'To destroy or reverse' },
  unsay: { base: 'unsay', v2: 'unsaid', v3: 'unsaid', s: 'unsays', ing: 'unsaying', type: 'irregular', meaning: 'To retract a statement' },
  unstick: { base: 'unstick', v2: 'unstuck', v3: 'unstuck', s: 'unsticks', ing: 'unsticking', type: 'irregular', meaning: 'To free from being stuck' },
  unstring: { base: 'unstring', v2: 'unstrung', v3: 'unstrung', s: 'unstrings', ing: 'unstringing', type: 'irregular', meaning: 'To relax or unfasten' },
  unteach: { base: 'unteach', v2: 'untaught', v3: 'untaught', s: 'unteaches', ing: 'unteaching', type: 'irregular', meaning: 'To make someone forget' },
  unthink: { base: 'unthink', v2: 'unthought', v3: 'unthought', s: 'unthinks', ing: 'unthinking', type: 'irregular', meaning: 'To discard a thought' },
  unwind: { base: 'unwind', v2: 'unwound', v3: 'unwound', s: 'unwinds', ing: 'unwinding', type: 'irregular', meaning: 'To relax or unroll' },
  uphold: { base: 'uphold', v2: 'upheld', v3: 'upheld', s: 'upholds', ing: 'upholding', type: 'irregular', meaning: 'To confirm or support' },
  wake: { base: 'wake', v2: 'woke', v3: 'woken', s: 'wakes', ing: 'waking', type: 'irregular', meaning: 'To stop sleeping' },
  waylay: { base: 'waylay', v2: 'waylaid', v3: 'waylaid', s: 'waylays', ing: 'waylaying', type: 'irregular', meaning: 'To intercept or ambush' },
  wear: { base: 'wear', v2: 'wore', v3: 'worn', s: 'wears', ing: 'wearing', type: 'irregular', meaning: 'To have on one\'s body' },
  weave: { base: 'weave', v2: 'wove', v3: 'woven', s: 'weaves', ing: 'weaving', type: 'irregular', meaning: 'To form fabric by interlacing' },
  weep: { base: 'weep', v2: 'wept', v3: 'wept', s: 'weeps', ing: 'weeping', type: 'irregular', meaning: 'To cry tears' },
  win: { base: 'win', v2: 'won', v3: 'won', s: 'wins', ing: 'winning', type: 'irregular', meaning: 'To be successful' },
  wind: { base: 'wind', v2: 'wound', v3: 'wound', s: 'winds', ing: 'winding', type: 'irregular', meaning: 'To twist or encircle' },
  withdraw: { base: 'withdraw', v2: 'withdrew', v3: 'withdrawn', s: 'withdraws', ing: 'withdrawing', type: 'irregular', meaning: 'To remove or take away' },
  withhold: { base: 'withhold', v2: 'withheld', v3: 'withheld', s: 'withholds', ing: 'withholding', type: 'irregular', meaning: 'To refuse to give something' },
  withstand: { base: 'withstand', v2: 'withstood', v3: 'withstood', s: 'withstands', ing: 'withstanding', type: 'irregular', meaning: 'To remain undamaged or unaffected by' },
  write: { base: 'write', v2: 'wrote', v3: 'written', s: 'writes', ing: 'writing', type: 'irregular', meaning: 'To mark letters on a surface' },
  wring: { base: 'wring', v2: 'wrung', v3: 'wrung', s: 'wrings', ing: 'wringing', type: 'irregular', meaning: 'To twist and squeeze' },
};

export const LESSONS: Lesson[] = [lesson1, lesson2, lesson3];
